#!/usr/bin/env python3
"""CPJ -> standalone web emitter.

Generates one self-contained HTML file from CPJ `web { ... }` blocks.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import shlex
import sys
from pathlib import Path
from typing import Iterable

from tools.cpj_parser import Module, Print, Str, WebBlock, parse_file


DEFAULT_THEME = {
    "background": "#f6f8fb",
    "surface": "#ffffff",
    "surface_alt": "#edf7f4",
    "text": "#18212f",
    "muted": "#617085",
    "primary": "#1f6feb",
    "accent": "#c55a11",
    "border": "#d8dee8",
}


class WebEmitter:
    """Emit a CPJ module as a standalone HTML document."""

    def __init__(self):
        self.title = "CPJ Web App"
        self.description = "Standalone web application generated by CPJ."
        self.theme = dict(DEFAULT_THEME)
        self.nav_items: list[tuple[str, str]] = []
        self.body_parts: list[str] = []
        self.states: dict[str, str] = {}
        self.components: dict[str, str] = {}
        self.routes: list[dict[str, str]] = []
        self.api_routes: list[dict[str, object]] = []
        self.models: dict[str, list[dict[str, str | bool]]] = {}
        self.custom_css: list[str] = []
        self.custom_js: list[str] = []
        self.pwa: dict[str, object] | None = None
        self.uploads: list[dict[str, object]] = []
        self.stores: dict[str, dict[str, object]] = {}
        self.middleware: list[dict[str, object]] = []
        self.pipelines: list[dict[str, object]] = []
        self.guards: list[dict[str, object]] = []
        self.services: dict[str, dict[str, object]] = {}
        self.migrations: list[dict[str, object]] = []
        self.templates: dict[str, str] = {}
        self.bundle: dict[str, object] = {}
        self.marketplace: dict[str, object] = {"name": "CPJ Marketplace", "registry": "local", "plugins": [], "hooks": {}}
        self.diagnostics_messages: list[dict[str, str]] = []
        self.seen_h1 = 0
        self.server_host = "127.0.0.1"
        self.server_port = 8080
        self.cms: dict[str, object] | None = None

    def emit(self, node: Module) -> str:
        web_blocks = [item for item in node.items if isinstance(item, WebBlock)]

        if web_blocks:
            for block in web_blocks:
                self._emit_web_block(block)
        else:
            self._emit_fallback(node.items)

        return self._document()

    def _emit_web_block(self, block: WebBlock) -> None:
        rendered, _ = self._emit_lines(block.lines, 0)
        self.body_parts.append(rendered)

    def _emit_fallback(self, items: Iterable[object]) -> None:
        output = []
        for item in items:
            if isinstance(item, Print) and isinstance(item.expr, Str):
                output.append(self._tag("p", item.expr.s))

        if not output:
            output.append(
                self._tag(
                    "p",
                    "No web block found. Add `web { ... }` to emit a browser page.",
                    "cpj-muted",
                )
            )

        self.body_parts.append(
            self._block(
                "section",
                [
                    self._tag("h1", self.title),
                    *output,
                ],
                {"class": "cpj-section cpj-section--hero"},
            )
        )

    def _emit_lines(self, lines: list[str], start: int, context: str | None = None) -> tuple[str, int]:
        parts = []
        index = start

        while index < len(lines):
            line = lines[index].strip()
            index += 1

            if not line or line.startswith("#") or line.startswith("//"):
                continue
            if line == "}":
                break

            if line.endswith("{"):
                command = line[:-1].strip()
                if self._raw_block_kind(command) in {
                    "api",
                    "animation",
                    "cms",
                    "container",
                    "guard",
                    "migration",
                    "middleware",
                    "model",
                    "pipeline",
                    "service",
                    "store",
                    "upload",
                    "bundle",
                    "marketplace",
                }:
                    raw_lines, index = self._collect_raw_block(lines, index)
                    rendered = self._emit_raw_block(command, raw_lines)
                else:
                    inner, index = self._emit_lines(lines, index, self._child_context(command, context))
                    rendered = self._emit_block(command, inner)
            else:
                rendered = self._emit_statement(line, context)

            if rendered:
                parts.append(rendered)

        return "\n".join(parts), index

    def _raw_block_kind(self, command: str) -> str:
        tokens = self._split(command)
        return tokens[0].lower() if tokens else ""

    def _collect_raw_block(self, lines: list[str], start: int) -> tuple[list[str], int]:
        raw_lines = []
        index = start
        depth = 1

        while index < len(lines) and depth > 0:
            line = lines[index].strip()
            index += 1

            opens = line.count("{")
            closes = line.count("}")
            depth += opens - closes

            if depth <= 0 and line == "}":
                continue
            raw_lines.append(line)

        return raw_lines, index

    def _child_context(self, command: str, context: str | None) -> str | None:
        tokens = self._split(command)
        if tokens and tokens[0].lower() == "form":
            return "form"
        return context

    def _emit_block(self, command: str, inner: str) -> str:
        tokens = self._split(command)
        if not tokens:
            return inner

        kind = tokens[0].lower()
        name = tokens[1] if len(tokens) > 1 else kind

        if kind in {"section", "hero"}:
            section_name = name if kind == "section" else "hero"
            section_id = self._slug(section_name)
            classes = f"cpj-section cpj-section--{section_id}"
            return self._wrap("section", inner, {"id": section_id, "class": classes})

        if kind == "grid":
            return self._wrap("div", inner, {"class": "cpj-grid"})

        if kind == "card":
            title = tokens[1] if len(tokens) > 1 else ""
            heading = self._tag("h3", title) if title else ""
            return self._wrap("article", heading + inner, {"class": "cpj-card"})

        if kind == "component":
            component_name = self._slug(name)
            self.components[component_name] = inner
            return ""

        if kind == "template":
            template_name = self._slug(name)
            self.templates[template_name] = inner
            self.components[template_name] = inner
            return ""

        if kind == "route":
            route_path = name if name.startswith("/") else f"/{name}"
            template_name = self._template_from_tokens(tokens[2:])
            if template_name:
                inner = self._apply_template(template_name, inner)
            self.routes.append({"path": route_path, "html": inner})
            return ""

        if kind == "form":
            form_id = self._slug(name)
            attrs = self._form_attrs(form_id, tokens[2:])
            return self._wrap(
                "form",
                inner,
                attrs,
            )

        if kind in {"header", "main", "footer", "aside", "nav"}:
            return self._wrap(kind, inner, {"class": f"cpj-{kind}"})

        return self._wrap("div", inner, {"class": f"cpj-block cpj-block--{self._slug(kind)}"})

    def _emit_raw_block(self, command: str, raw_lines: list[str]) -> str:
        tokens = self._split(command)
        if not tokens:
            return ""

        kind = tokens[0].lower()
        name = tokens[1] if len(tokens) > 1 else kind

        if kind == "api":
            path = name if name.startswith("/") else f"/{name}"
            payload: dict[str, object] = {}
            method = "GET"
            inject: list[str] = []
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                if parts[0].lower() == "method" and len(parts) > 1:
                    method = parts[1].upper()
                elif parts[0].lower() == "json" and len(parts) > 2:
                    payload[self._slug(parts[1])] = self._coerce_value(" ".join(parts[2:]))
                elif parts[0].lower() == "inject" and len(parts) > 1:
                    inject.extend(self._slug(part) for part in parts[1:])
            self.api_routes.append({"path": path, "method": method, "json": payload, "inject": inject})
            return ""

        if kind == "service":
            service_name = self._slug(name)
            service: dict[str, object] = {"name": service_name, "values": {}, "env": {}, "singleton": True}
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                command = parts[0].lower().replace("-", "_")
                if command == "value" and len(parts) > 2:
                    service["values"][self._slug(parts[1])] = self._coerce_value(" ".join(parts[2:]))
                elif command == "env" and len(parts) > 2:
                    service["env"][self._slug(parts[1])] = {
                        "name": parts[2],
                        "default": self._coerce_value(" ".join(parts[3:])) if len(parts) > 3 else "",
                    }
                elif command == "singleton" and len(parts) > 1:
                    service["singleton"] = bool(self._coerce_value(parts[1]))
            self.services[service_name] = service
            return ""

        if kind == "model":
            fields = []
            for line in raw_lines:
                parts = self._split(line)
                if len(parts) >= 3 and parts[0].lower() == "field":
                    fields.append(
                        {
                            "name": self._slug(parts[1]),
                            "type": parts[2],
                            "required": any(part.lower() == "required" for part in parts[3:]),
                        }
                    )
            self.models[self._slug(name)] = fields
            return ""

        if kind == "store":
            store_name = self._slug(name)
            store: dict[str, object] = {
                "name": store_name,
                "path": f"/api/store/{store_name}",
                "fields": [],
                "seed": [],
            }
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                command = parts[0].lower()
                if command == "path" and len(parts) > 1:
                    store["path"] = parts[1]
                elif command == "field" and len(parts) >= 3:
                    store["fields"].append(
                        {
                            "name": self._slug(parts[1]),
                            "type": parts[2],
                            "required": any(part.lower() == "required" for part in parts[3:]),
                        }
                    )
                elif command == "seed" and len(parts) > 2:
                    row = {}
                    index = 1
                    while index + 1 < len(parts):
                        row[self._slug(parts[index])] = self._coerce_value(parts[index + 1])
                        index += 2
                    if row:
                        store["seed"].append(row)
            self.stores[store_name] = store
            return ""

        if kind == "migration":
            migration_name = self._slug(name)
            migration: dict[str, object] = {"name": migration_name, "store": "", "add_fields": [], "indexes": []}
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                command = parts[0].lower().replace("-", "_")
                if command == "store" and len(parts) > 1:
                    migration["store"] = self._slug(parts[1])
                elif command in {"add_field", "field"} and len(parts) >= 3:
                    field = {
                        "name": self._slug(parts[1]),
                        "type": parts[2],
                        "required": any(part.lower() == "required" for part in parts[3:]),
                    }
                    migration["add_fields"].append(field)
                elif command == "index" and len(parts) > 1:
                    migration["indexes"].append(
                        {
                            "field": self._slug(parts[1]),
                            "unique": any(part.lower() == "unique" for part in parts[2:]),
                        }
                    )
            if not migration["store"]:
                migration["store"] = migration_name
            store = self.stores.get(str(migration["store"]))
            if store:
                existing = {field["name"] for field in store.get("fields", [])}
                for field in migration["add_fields"]:
                    if field["name"] not in existing:
                        store["fields"].append(field)
            self.migrations.append(migration)
            return ""

        if kind == "upload":
            upload_name = self._slug(name)
            upload: dict[str, object] = {
                "name": upload_name,
                "path": f"/api/uploads/{upload_name}",
                "dir": f"uploads/{upload_name}",
                "accept": [],
                "max_bytes": 5 * 1024 * 1024,
            }
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                command = parts[0].lower().replace("-", "_")
                if command == "path" and len(parts) > 1:
                    upload["path"] = parts[1]
                elif command in {"dir", "directory"} and len(parts) > 1:
                    upload["dir"] = parts[1]
                elif command == "accept" and len(parts) > 1:
                    upload["accept"] = [item.strip() for item in " ".join(parts[1:]).split(",") if item.strip()]
                elif command in {"max", "max_bytes", "maxbytes"} and len(parts) > 1:
                    upload["max_bytes"] = int(parts[1])
            self.uploads.append(upload)
            return ""

        if kind == "middleware":
            middleware: dict[str, object] = {
                "name": self._slug(name),
                "headers": {},
                "cors": "",
                "log": False,
                "request_id": False,
                "require_headers": [],
            }
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                command = parts[0].lower().replace("-", "_")
                if command == "header" and len(parts) > 2:
                    middleware["headers"][" ".join(parts[1:-1])] = parts[-1]
                elif command == "cors":
                    middleware["cors"] = parts[1] if len(parts) > 1 else "*"
                elif command == "log" and len(parts) > 1:
                    middleware["log"] = bool(self._coerce_value(parts[1]))
                elif command == "request_id" and len(parts) > 1:
                    middleware["request_id"] = bool(self._coerce_value(parts[1]))
                elif command == "require_header" and len(parts) > 2:
                    middleware["require_headers"].append(self._require_header(parts[1:]))
            self.middleware.append(middleware)
            return ""

        if kind == "pipeline":
            pipeline: dict[str, object] = {
                "name": self._slug(name),
                "uses": [],
                "headers": {},
                "cors": "",
                "log": False,
                "request_id": False,
                "require_headers": [],
            }
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                command = parts[0].lower().replace("-", "_")
                if command == "use" and len(parts) > 1:
                    pipeline["uses"].extend(self._slug(part) for part in parts[1:])
                elif command == "header" and len(parts) > 2:
                    pipeline["headers"][" ".join(parts[1:-1])] = parts[-1]
                elif command == "cors":
                    pipeline["cors"] = parts[1] if len(parts) > 1 else "*"
                elif command == "log" and len(parts) > 1:
                    pipeline["log"] = bool(self._coerce_value(parts[1]))
                elif command == "request_id" and len(parts) > 1:
                    pipeline["request_id"] = bool(self._coerce_value(parts[1]))
                elif command == "require_header" and len(parts) > 2:
                    pipeline["require_headers"].append(self._require_header(parts[1:]))
            self.pipelines.append(pipeline)
            return ""

        if kind == "guard":
            guard: dict[str, object] = {"name": self._slug(name), "path": name if name.startswith("/") else "", "token": ""}
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                command = parts[0].lower()
                if command == "path" and len(parts) > 1:
                    guard["path"] = parts[1]
                elif command == "token" and len(parts) > 1:
                    guard["token"] = parts[1]
            if guard["path"]:
                self.guards.append(guard)
            return ""

        if kind == "container":
            selector = ".cpj-section"
            min_width = "420px"
            rules: list[str] = []
            container_name = self._slug(name)
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                command = parts[0].lower().replace("-", "_")
                if command == "selector" and len(parts) > 1:
                    selector = parts[1]
                elif command in {"min", "min_width"} and len(parts) > 1:
                    min_width = parts[1]
                elif command in {"css", "rule"} and len(parts) > 1:
                    rules.append(" ".join(parts[1:]))
            self.custom_css.append(f"{selector} {{ container-type: inline-size; container-name: {container_name}; }}")
            if rules:
                self.custom_css.append(f"@container {container_name} (min-width: {min_width}) {{ {' '.join(rules)} }}")
            return ""

        if kind == "animation":
            animation_name = self._slug(name).replace("-", "_")
            duration = "320ms"
            timing = "ease"
            from_rule = "opacity: 0;"
            to_rule = "opacity: 1;"
            apply_selector = ""
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                command = parts[0].lower()
                if command == "duration" and len(parts) > 1:
                    duration = parts[1]
                elif command == "timing" and len(parts) > 1:
                    timing = parts[1]
                elif command == "from" and len(parts) > 1:
                    from_rule = " ".join(parts[1:])
                elif command == "to" and len(parts) > 1:
                    to_rule = " ".join(parts[1:])
                elif command == "apply" and len(parts) > 1:
                    apply_selector = parts[1]
            self.custom_css.append(f"@keyframes {animation_name} {{ from {{ {from_rule} }} to {{ {to_rule} }} }}")
            if apply_selector:
                self.custom_css.append(f"{apply_selector} {{ animation: {animation_name} {duration} {timing} both; }}")
            return ""

        if kind == "bundle":
            bundle_name = self._slug(name)
            bundle: dict[str, object] = {
                "name": bundle_name,
                "target": "es2022",
                "module": "esm",
                "types": True,
                "exports": ["CPJ"],
            }
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                command = parts[0].lower()
                if command in {"target", "module"} and len(parts) > 1:
                    bundle[command] = parts[1]
                elif command == "types" and len(parts) > 1:
                    bundle["types"] = bool(self._coerce_value(parts[1]))
                elif command == "export" and len(parts) > 1:
                    bundle.setdefault("exports", [])
                    bundle["exports"].extend(parts[1:])
            self.bundle = bundle
            return ""

        if kind == "marketplace":
            marketplace = {
                "name": " ".join(tokens[1:]) if len(tokens) > 1 else "CPJ Marketplace",
                "registry": "local",
                "plugins": [],
                "hooks": {},
            }
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                command = parts[0].lower()
                if command == "registry" and len(parts) > 1:
                    marketplace["registry"] = parts[1]
                elif command == "plugin" and len(parts) > 3:
                    marketplace["plugins"].append(
                        {
                            "slug": self._slug(parts[1]),
                            "name": parts[2],
                            "version": parts[3],
                            "description": " ".join(parts[4:]) if len(parts) > 4 else "",
                            "status": "active",
                        }
                    )
                elif command == "hook" and len(parts) > 3:
                    plugin = self._slug(parts[1])
                    hook_name = self._slug(parts[2])
                    marketplace["hooks"].setdefault(hook_name, [])
                    marketplace["hooks"][hook_name].append({"plugin": plugin, "html": " ".join(parts[3:])})
            self.marketplace = marketplace
            return ""

        if kind == "cms":
            config: dict[str, object] = {
                "name": name,
                "admin_path": "/admin",
                "blog_path": "/blog",
                "storage": f"{self._slug(name)}_content.json",
                "posts": [],
                "pages": [],
                "categories": [],
                "comments": [],
                "media": [],
                "users": [],
                "plugins": [],
                "settings": {},
            }
            for line in raw_lines:
                parts = self._split(line)
                if not parts:
                    continue
                command = parts[0].lower()
                if command == "admin" and len(parts) > 1:
                    config["admin_path"] = parts[1]
                elif command == "blog" and len(parts) > 1:
                    config["blog_path"] = parts[1]
                elif command == "storage" and len(parts) > 1:
                    config["storage"] = parts[1]
                elif command == "site" and len(parts) > 1:
                    config["name"] = " ".join(parts[1:])
                elif command == "category" and len(parts) > 1:
                    config["categories"].append(" ".join(parts[1:]))
                elif command == "setting" and len(parts) > 2:
                    config["settings"][self._slug(parts[1])] = self._coerce_value(" ".join(parts[2:]))
                elif command == "user" and len(parts) > 3:
                    username = self._slug(parts[1])
                    password = parts[2]
                    config["users"].append(
                        {
                            "username": username,
                            "display_name": " ".join(parts[4:]) if len(parts) > 4 else username,
                            "role": parts[3],
                            "password_hash": self._cms_password_hash(username, password),
                        }
                    )
                elif command == "post" and len(parts) > 3:
                    config["posts"].append(
                        {
                            "slug": self._slug(parts[1]),
                            "title": parts[2],
                            "body": " ".join(parts[3:]),
                            "type": "post",
                            "status": "published",
                            "author": "CPJ",
                        }
                    )
                elif command == "page" and len(parts) > 3:
                    config["pages"].append(
                        {
                            "slug": self._slug(parts[1]),
                            "title": parts[2],
                            "body": " ".join(parts[3:]),
                            "type": "page",
                            "status": "published",
                            "author": "CPJ",
                        }
                    )
                elif command == "comment" and len(parts) > 3:
                    config["comments"].append(
                        {
                            "id": f"seed-{len(config['comments']) + 1}",
                            "post": self._slug(parts[1]),
                            "author": parts[2],
                            "body": " ".join(parts[3:]),
                            "status": "approved",
                        }
                    )
                elif command == "media" and len(parts) > 3:
                    config["media"].append(
                        {
                            "slug": self._slug(parts[1]),
                            "title": parts[2],
                            "url": parts[3],
                            "alt": " ".join(parts[4:]) if len(parts) > 4 else parts[2],
                        }
                    )
                elif command == "plugin" and len(parts) > 2:
                    config["plugins"].append(
                        {
                            "slug": self._slug(parts[1]),
                            "name": parts[2],
                            "description": " ".join(parts[3:]) if len(parts) > 3 else "",
                            "status": "active",
                        }
                    )
            self.cms = config
            return ""

        return ""

    def _emit_statement(self, line: str, context: str | None = None) -> str:
        tokens = self._split(line)
        if not tokens:
            return ""

        kind = tokens[0].lower()

        if kind == "title" and len(tokens) > 1:
            self.title = " ".join(tokens[1:])
            return ""

        if kind == "meta" and len(tokens) > 2:
            if tokens[1].lower() == "description":
                self.description = " ".join(tokens[2:])
            return ""

        if kind == "pwa":
            name = " ".join(tokens[1:]) if len(tokens) > 1 else self.title
            self.pwa = {
                "name": name or self.title,
                "short_name": (name or self.title)[:24],
                "start_url": "/",
                "display": "standalone",
            }
            return ""

        if kind in {"theme", "style"} and len(tokens) > 2:
            key = tokens[1].replace("-", "_")
            self.theme[key] = tokens[2]
            return ""

        if kind == "server" and len(tokens) > 2:
            option = tokens[1].lower()
            if option == "host":
                self.server_host = tokens[2]
            elif option == "port":
                self.server_port = int(tokens[2])
            return ""

        if kind == "css" and len(tokens) > 1:
            self.custom_css.append(" ".join(tokens[1:]))
            return ""

        if kind in {"js", "javascript"} and len(tokens) > 1:
            self.custom_js.append(" ".join(tokens[1:]))
            return ""

        if kind == "html" and len(tokens) > 1:
            return " ".join(tokens[1:])

        if kind == "state" and len(tokens) > 2:
            self.states[self._slug(tokens[1])] = " ".join(tokens[2:])
            return ""

        if kind == "slot":
            slot_name = self._slug(tokens[1]) if len(tokens) > 1 else "content"
            return "{{" + slot_name + "}}"

        if kind == "nav" and len(tokens) > 2:
            self.nav_items.append((tokens[1], tokens[2]))
            return ""

        if kind in {"h1", "h2", "h3", "h4", "p", "small", "code"}:
            tag = "p" if kind == "small" else kind
            css = "cpj-small" if kind == "small" else None
            if kind == "h1":
                self.seen_h1 += 1
            return self._tag(tag, " ".join(tokens[1:]), css)

        if kind == "text":
            return self._tag("p", " ".join(tokens[1:]))

        if kind == "badge" and len(tokens) > 1:
            return self._tag("span", " ".join(tokens[1:]), "cpj-badge")

        if kind == "link" and len(tokens) > 2:
            return self._link(tokens[1], tokens[2], "cpj-link")

        if kind == "use" and len(tokens) > 1:
            component_name = self._slug(tokens[1])
            return self.components.get(
                component_name,
                f"<!-- CPJ web: missing component {self._text(tokens[1])} -->",
            )

        if kind == "button" and len(tokens) > 1:
            label = tokens[1]
            target = self._target_from_tokens(tokens[2:])
            if target:
                return self._link(label, target, "cpj-button")
            button_type = "submit" if context == "form" else "button"
            return self._tag(
                "button",
                label,
                "cpj-button",
                {"type": button_type, "data-cpj-action": self._slug(label)},
            )

        if kind == "card" and len(tokens) > 2:
            return self._block(
                "article",
                [self._tag("h3", tokens[1]), self._tag("p", " ".join(tokens[2:]))],
                {"class": "cpj-card"},
            )

        if kind == "image" and len(tokens) > 1:
            src = tokens[1]
            alt = tokens[2] if len(tokens) > 2 else ""
            if not alt:
                self.diagnostics_messages.append(
                    {
                        "level": "warning",
                        "area": "accessibility",
                        "message": f"Image {src} is missing alt text.",
                    }
                )
            return f'<img class="cpj-image" src="{self._attr(src)}" alt="{self._attr(alt)}">'

        if kind == "input" and len(tokens) > 2:
            name = self._slug(tokens[1])
            label = tokens[2]
            input_type = tokens[3] if len(tokens) > 3 else "text"
            return self._field(name, label, input_type, tokens[4:])

        if kind == "textarea" and len(tokens) > 2:
            name = self._slug(tokens[1])
            label = tokens[2]
            attrs = {"id": name, "name": name}
            self._apply_field_flags(attrs, tokens[3:])
            return (
                f'<label class="cpj-field" for="{self._attr(name)}">'
                f"<span>{self._text(label)}</span>"
                f"<textarea{self._attrs(attrs)}></textarea>"
                "</label>"
            )

        if kind == "select" and len(tokens) > 3:
            name = self._slug(tokens[1])
            label = tokens[2]
            attrs = {"id": name, "name": name}
            options_start = 3
            if len(tokens) > 4 and tokens[3].lower() == "required":
                self._apply_field_flags(attrs, ["required"])
                options_start = 4
            options = "\n".join(
                f'<option value="{self._attr(option)}">{self._text(option)}</option>'
                for option in tokens[options_start:]
            )
            return (
                f'<label class="cpj-field" for="{self._attr(name)}">'
                f"<span>{self._text(label)}</span>"
                f"<select{self._attrs(attrs)}>{options}</select>"
                "</label>"
            )

        if kind == "list" and len(tokens) > 1:
            items = "\n".join(f"<li>{self._text(item)}</li>" for item in tokens[1:])
            return f'<ul class="cpj-list">{items}</ul>'

        if kind == "counter" and len(tokens) > 2:
            name = self._slug(tokens[1])
            label = tokens[2]
            initial = tokens[3] if len(tokens) > 3 else "0"
            return self._counter(name, label, initial)

        return f"<!-- CPJ web: ignored line {self._text(line)} -->"

    def _document(self) -> str:
        nav = self._nav()
        state_script = "\n".join(
            f"  CPJ.state[{key!r}] = {value!r};" for key, value in self.states.items()
        )
        body = "\n".join(self.body_parts)
        pwa_head = self._pwa_head()
        head_hooks = self._plugin_hook("head")
        body_end_hooks = self._plugin_hook("body_end")

        return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{self._attr(self.description)}">
{pwa_head}
{head_hooks}
  <title>{self._text(self.title)}</title>
  <style>
{self._css()}
  </style>
</head>
<body>
  <div class="cpj-app" data-cpj-app>
{nav}
    <main class="cpj-main">
{self._indent(body, 6)}
    </main>
  </div>
  <script>
{self._js(state_script)}
  </script>
{body_end_hooks}
</body>
</html>
"""

    def _nav(self) -> str:
        if not self.nav_items:
            return ""

        links = "\n".join(
            f'      <a href="{self._attr(href)}">{self._text(label)}</a>'
            for label, href in self.nav_items
        )
        return f"""    <header class="cpj-topbar">
      <div class="cpj-brand">{self._text(self.title)}</div>
      <nav class="cpj-nav" aria-label="Primary">
{links}
      </nav>
    </header>"""

    def _css(self) -> str:
        css_vars = "\n".join(
            f"  --cpj-{key.replace('_', '-')}: {value};" for key, value in self.theme.items()
        )
        custom_css = "\n".join(f"    {line}" for line in self.custom_css)
        return f"""    :root {{
{css_vars}
      --cpj-radius: 8px;
      --cpj-shadow: 0 18px 48px rgba(24, 33, 47, 0.10);
    }}
    * {{ box-sizing: border-box; }}
    html {{ scroll-behavior: smooth; }}
    body {{
      margin: 0;
      background: var(--cpj-background);
      color: var(--cpj-text);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.55;
    }}
    a {{ color: inherit; }}
    .cpj-app {{ min-height: 100vh; }}
    .cpj-topbar {{
      position: sticky;
      top: 0;
      z-index: 5;
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 24px;
      padding: 14px clamp(18px, 4vw, 56px);
      border-bottom: 1px solid color-mix(in srgb, var(--cpj-border), transparent 20%);
      background: color-mix(in srgb, var(--cpj-surface), transparent 8%);
      backdrop-filter: blur(16px);
    }}
    .cpj-brand {{ font-weight: 750; }}
    .cpj-nav {{ display: flex; flex-wrap: wrap; gap: 12px; color: var(--cpj-muted); font-size: 0.95rem; }}
    .cpj-nav a {{ text-decoration: none; }}
    .cpj-nav a:hover {{ color: var(--cpj-text); }}
    .cpj-main {{ width: min(1120px, calc(100% - 32px)); margin: 0 auto; }}
    .cpj-section {{ padding: clamp(44px, 8vw, 96px) 0; }}
    .cpj-section--hero {{
      min-height: 68vh;
      display: grid;
      align-content: center;
      border-bottom: 1px solid var(--cpj-border);
    }}
    h1, h2, h3, h4, p {{ margin-top: 0; }}
    h1 {{ max-width: 920px; font-size: clamp(2.6rem, 8vw, 5.7rem); line-height: 0.98; letter-spacing: 0; }}
    h2 {{ font-size: clamp(1.9rem, 4vw, 3.1rem); line-height: 1.05; letter-spacing: 0; }}
    h3 {{ font-size: 1.15rem; letter-spacing: 0; }}
    p {{ max-width: 760px; color: var(--cpj-muted); }}
    .cpj-small {{ font-size: 0.92rem; color: var(--cpj-muted); }}
    .cpj-muted {{ color: var(--cpj-muted); }}
    .cpj-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 240px), 1fr)); gap: 16px; }}
    .cpj-card {{
      min-height: 160px;
      padding: 22px;
      border: 1px solid var(--cpj-border);
      border-radius: var(--cpj-radius);
      background: var(--cpj-surface);
      box-shadow: var(--cpj-shadow);
    }}
    .cpj-card p {{ margin-bottom: 0; }}
    .cpj-button {{
      display: inline-flex;
      align-items: center;
      justify-content: center;
      min-height: 44px;
      margin: 8px 10px 8px 0;
      padding: 0 18px;
      border: 1px solid transparent;
      border-radius: var(--cpj-radius);
      background: var(--cpj-primary);
      color: white;
      font: inherit;
      font-weight: 700;
      text-decoration: none;
      cursor: pointer;
    }}
    .cpj-button:hover {{ filter: brightness(0.96); }}
    .cpj-link {{ color: var(--cpj-primary); font-weight: 700; text-decoration-thickness: 2px; }}
    .cpj-badge {{
      display: inline-flex;
      padding: 4px 9px;
      border: 1px solid var(--cpj-border);
      border-radius: 999px;
      color: var(--cpj-accent);
      background: var(--cpj-surface-alt);
      font-size: 0.84rem;
      font-weight: 800;
    }}
    .cpj-form {{ display: grid; gap: 14px; max-width: 680px; }}
    .cpj-field {{ display: grid; gap: 7px; color: var(--cpj-muted); font-weight: 700; }}
    input, textarea, select {{
      width: 100%;
      border: 1px solid var(--cpj-border);
      border-radius: var(--cpj-radius);
      padding: 12px 13px;
      color: var(--cpj-text);
      background: var(--cpj-surface);
      font: inherit;
    }}
    textarea {{ min-height: 132px; resize: vertical; }}
    .cpj-form-status {{ color: var(--cpj-accent); font-weight: 800; }}
    .cpj-list {{ padding-left: 1.2rem; color: var(--cpj-muted); }}
    .cpj-counter {{
      display: inline-grid;
      grid-template-columns: auto auto auto;
      align-items: center;
      gap: 8px;
      padding: 8px;
      border: 1px solid var(--cpj-border);
      border-radius: var(--cpj-radius);
      background: var(--cpj-surface);
    }}
    .cpj-counter strong {{ min-width: 3ch; text-align: center; }}
    .cpj-counter button {{
      width: 36px;
      height: 36px;
      border: 1px solid var(--cpj-border);
      border-radius: var(--cpj-radius);
      background: var(--cpj-surface-alt);
      color: var(--cpj-text);
      font: inherit;
      cursor: pointer;
    }}
    .cpj-image {{ max-width: 100%; border-radius: var(--cpj-radius); border: 1px solid var(--cpj-border); }}
{custom_css}
    @media (max-width: 720px) {{
      .cpj-topbar {{ align-items: flex-start; flex-direction: column; }}
      .cpj-section--hero {{ min-height: auto; }}
    }}"""

    def _js(self, state_script: str) -> str:
        custom_js = "\n".join(f"    {line}" for line in self.custom_js)
        pwa_js = ""
        if self.pwa:
            pwa_js = """
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', () => {
        navigator.serviceWorker.register('/sw.js').catch(() => {});
      });
    }
"""
        return f"""    const CPJ = window.CPJ = {{
      state: {{}},
      event(name, detail = {{}}) {{
        document.dispatchEvent(new CustomEvent(`cpj:${{name}}`, {{ detail }}));
      }},
      async submit(form, data) {{
        const endpoint = form.dataset.cpjEndpoint;
        if (!endpoint) return {{ ok: true, local: true }};
        const method = form.dataset.cpjMethod || form.method || 'POST';
        const isGet = method.toUpperCase() === 'GET';
        const url = isGet ? `${{endpoint}}?${{new URLSearchParams(data)}}` : endpoint;
        const isMultipart = form.dataset.cpjEncoding === 'multipart' || Boolean(form.querySelector('input[type="file"]'));
        const body = isGet ? undefined : (isMultipart ? new FormData(form) : JSON.stringify(data));
        const headers = isMultipart || isGet ? {{}} : {{ 'Content-Type': 'application/json' }};
        const response = await fetch(url, {{
          method,
          headers,
          body
        }});
        const contentType = response.headers.get('content-type') || '';
        const payload = contentType.includes('application/json') ? await response.json() : await response.text();
        return {{ ok: response.ok, status: response.status, payload }};
      }}
    }};
{state_script}

    document.querySelectorAll('[data-cpj-form]').forEach((form) => {{
      const status = document.createElement('p');
      status.className = 'cpj-form-status';
      status.setAttribute('role', 'status');
      form.appendChild(status);
      form.addEventListener('submit', (event) => {{
        event.preventDefault();
        const data = Object.fromEntries(new FormData(form).entries());
        CPJ.event('form-submit', {{ id: form.dataset.cpjForm, data }});
        CPJ.submit(form, data)
          .then((result) => {{
            status.textContent = result.local
              ? 'Submitted locally. Hook cpj:form-submit to connect services.'
              : (result.ok ? 'Submitted to CPJ server.' : `Server returned ${{result.status}}.`);
            CPJ.event('form-response', {{ id: form.dataset.cpjForm, result }});
          }})
          .catch((error) => {{
            status.textContent = 'Submission failed.';
            CPJ.event('form-error', {{ id: form.dataset.cpjForm, error: String(error) }});
          }});
      }});
    }});

    document.querySelectorAll('[data-cpj-counter]').forEach((counter) => {{
      const value = counter.querySelector('[data-cpj-counter-value]');
      let count = Number(counter.dataset.initial || 0);
      const render = () => value.textContent = String(count);
      counter.addEventListener('click', (event) => {{
        const action = event.target && event.target.dataset ? event.target.dataset.counterAction : null;
        if (action === 'inc') count += 1;
        if (action === 'dec') count -= 1;
        render();
        CPJ.event('counter-change', {{ id: counter.dataset.cpjCounter, value: count }});
      }});
      render();
    }});
{pwa_js}
{custom_js}"""

    def _pwa_head(self) -> str:
        if not self.pwa:
            return ""
        return (
            f'  <meta name="theme-color" content="{self._attr(self.theme.get("primary", "#2457c5"))}">\n'
            '  <link rel="manifest" href="/manifest.webmanifest">'
        )

    def _cms_seed(self) -> list[dict[str, object]]:
        if not self.cms:
            return []
        posts = list(self.cms.get("posts", []))
        posts.extend(self.cms.get("pages", []))
        for index, post in enumerate(posts):
            post.setdefault("created_at", f"2026-05-19T00:00:{index:02d}+00:00")
        return posts

    def _cms_password_hash(self, username: str, password: str) -> str:
        salt = f"cpjpress-{self._slug(username)}"
        digest = hashlib.sha256((salt + password).encode("utf-8")).hexdigest()
        return f"sha256${salt}${digest}"

    def _cms_seed_store(self) -> dict[str, object]:
        if not self.cms:
            return {}
        users = list(self.cms.get("users", []))
        if not users:
            users.append(
                {
                    "username": "admin",
                    "display_name": "Administrator",
                    "role": "admin",
                    "password_hash": self._cms_password_hash("admin", "admin"),
                    "created_at": "2026-05-19T00:00:00+00:00",
                }
            )
        store = {
            "posts": self._cms_seed(),
            "comments": list(self.cms.get("comments", [])),
            "media": list(self.cms.get("media", [])),
            "users": users,
            "sessions": {},
            "settings": dict(self.cms.get("settings", {})),
            "plugins": list(self.cms.get("plugins", [])),
        }
        for collection in ("comments", "media", "plugins"):
            for index, item in enumerate(store[collection]):
                item.setdefault("created_at", f"2026-05-19T00:01:{index:02d}+00:00")
        return store

    def runtime_assets(self) -> dict[str, dict[str, str]]:
        assets: dict[str, dict[str, str]] = {}
        if self.bundle:
            assets[f"/{self.bundle.get('name', 'app')}.bundle.js"] = {
                "content_type": "text/javascript; charset=utf-8",
                "body": self.bundle_source(),
            }
        if not self.pwa:
            return assets
        manifest = {
            "name": self.pwa.get("name", self.title),
            "short_name": self.pwa.get("short_name", self.title[:24]),
            "start_url": self.pwa.get("start_url", "/"),
            "scope": "/",
            "display": self.pwa.get("display", "standalone"),
            "background_color": self.theme.get("background", "#f6f8fb"),
            "theme_color": self.theme.get("primary", "#2457c5"),
            "description": self.description,
            "icons": [],
        }
        cache_name = f"cpj-{self._slug(self.title)}-v1"
        precache = ["/", "/manifest.webmanifest"]
        worker = f"""const CPJ_CACHE = {json.dumps(cache_name)};
const CPJ_PRECACHE = {json.dumps(precache)};

self.addEventListener('install', (event) => {{
  event.waitUntil(caches.open(CPJ_CACHE).then((cache) => cache.addAll(CPJ_PRECACHE)));
}});

self.addEventListener('activate', (event) => {{
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== CPJ_CACHE).map((key) => caches.delete(key))))
  );
}});

self.addEventListener('fetch', (event) => {{
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request).then((cached) => {{
      if (cached) return cached;
      return fetch(event.request).then((response) => {{
        const copy = response.clone();
        caches.open(CPJ_CACHE).then((cache) => cache.put(event.request, copy));
        return response;
      }}).catch(() => caches.match('/'));
    }})
  );
}});
"""
        assets.update({
            "/manifest.webmanifest": {
                "content_type": "application/manifest+json; charset=utf-8",
                "body": json.dumps(manifest, indent=2),
            },
            "/sw.js": {
                "content_type": "text/javascript; charset=utf-8",
                "body": worker,
            },
        })
        return assets

    def bundle_source(self) -> str:
        state_script = "\n".join(
            f"CPJ.state[{key!r}] = {value!r};" for key, value in self.states.items()
        )
        return f"""// Generated CPJ browser bundle ({self.bundle.get('target', 'es2022')})
export const CPJ = window.CPJ || (window.CPJ = {{
  state: {{}},
  event(name, detail = {{}}) {{
    document.dispatchEvent(new CustomEvent(`cpj:${{name}}`, {{ detail }}));
  }}
}});
{state_script}
export const components = {json.dumps(sorted(self.components.keys()), indent=2)};
export const routes = {json.dumps([route["path"] for route in self.routes], indent=2)};
export default CPJ;
"""

    def bundle_types(self) -> str:
        return """export interface CPJRuntime {
  state: Record<string, string>;
  event(name: string, detail?: Record<string, unknown>): void;
}

export declare const CPJ: CPJRuntime;
export declare const components: string[];
export declare const routes: string[];
export default CPJ;
"""

    def server_source(self, index_html: str) -> str:
        routes = {"/": index_html}
        for route in self.routes:
            routes[str(route["path"])] = self._route_document(str(route["path"]), str(route["html"]))

        api_routes = {
            str(route["path"]): {
                "method": str(route.get("method", "GET")).upper(),
                "json": route.get("json", {}),
                "inject": route.get("inject", []),
            }
            for route in self.api_routes
        }
        assets = self.runtime_assets()

        if self.cms:
            return f'''#!/usr/bin/env python3
"""Generated CPJPress standalone CMS server.

Runs CPJ routes, APIs, publishing, comments, media metadata, feeds, sitemap,
sessions, and admin screens using only Python's standard library.
"""

from cpjpress_runtime import run_site

ROUTES = {routes!r}
API_ROUTES = {api_routes!r}
MODELS = {self.models!r}
CMS_CONFIG = {self.cms or {}!r}
CMS_SEED = {self._cms_seed_store()!r}
THEME = {self.theme!r}
COMPONENTS = {self.components!r}
ASSETS = {assets!r}
STORES = {self.stores!r}
UPLOADS = {self.uploads!r}
MIDDLEWARE = {self.middleware!r}
PIPELINES = {self.pipelines!r}
GUARDS = {self.guards!r}
MIGRATIONS = {self.migrations!r}
SERVICES = {self.services!r}
BUNDLE = {self.bundle!r}
MARKETPLACE = {self.marketplace!r}


if __name__ == "__main__":
    run_site(
        routes=ROUTES,
        api_routes=API_ROUTES,
        cms_config=CMS_CONFIG,
        cms_seed=CMS_SEED,
        theme=THEME,
        components=COMPONENTS,
        assets=ASSETS,
        stores=STORES,
        uploads=UPLOADS,
        middleware=MIDDLEWARE,
        pipelines=PIPELINES,
        guards=GUARDS,
        migrations=MIGRATIONS,
        services=SERVICES,
        marketplace=MARKETPLACE,
        host={self.server_host!r},
        port={self.server_port!r},
    )
'''

        return f'''#!/usr/bin/env python3
"""Generated CPJ standalone web server.

Runs server-rendered pages and JSON APIs without Flask, Django, ASP.NET, PHP,
Node, or external packages.
"""

from datetime import datetime, timezone
from html import escape
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse
import json
import mimetypes
import os
import re
import sqlite3
import uuid

ROUTES = {routes!r}
API_ROUTES = {api_routes!r}
ASSETS = {assets!r}
MODELS = {self.models!r}
CMS_CONFIG = {self.cms or {}!r}
CMS_SEED = {self._cms_seed()!r}
STORES = {self.stores!r}
UPLOADS = {self.uploads!r}
MIDDLEWARE = {self.middleware!r}
PIPELINES = {self.pipelines!r}
GUARDS = {self.guards!r}
MIGRATIONS = {self.migrations!r}
SERVICES = {self.services!r}
BUNDLE = {self.bundle!r}
MARKETPLACE = {self.marketplace!r}
STORE_DB = "cpj_store.sqlite3"


def cms_slug(value):
    slug = re.sub(r"[^a-zA-Z0-9_-]+", "-", str(value).strip().lower()).strip("-")
    return slug or "post"


def cms_storage_path():
    return Path(CMS_CONFIG.get("storage", "cpjpress_content.json"))


def cms_seed_content():
    return {{"posts": CMS_SEED}}


def cms_load():
    path = cms_storage_path()
    if not path.exists():
        cms_save(cms_seed_content())
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        data = cms_seed_content()
        cms_save(data)
    data.setdefault("posts", [])
    return data


def cms_save(data):
    cms_storage_path().write_text(json.dumps(data, indent=2), encoding="utf-8")


def cms_layout(title, body):
    site = escape(str(CMS_CONFIG.get("name", "CPJPress")))
    admin_path = escape(str(CMS_CONFIG.get("admin_path", "/admin")))
    blog_path = escape(str(CMS_CONFIG.get("blog_path", "/blog")))
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{escape(str(title))}} - {{site}}</title>
  <style>
    :root {{{{ --cpj-primary: #2457c5; --cpj-accent: #b25519; --cpj-border: #d8dee8; --cpj-text: #18212f; --cpj-muted: #617085; --cpj-surface: #fff; --cpj-bg: #f6f8fb; }}}}
    * {{{{ box-sizing: border-box; }}}}
    body {{{{ margin: 0; background: var(--cpj-bg); color: var(--cpj-text); font-family: Inter, ui-sans-serif, system-ui, sans-serif; line-height: 1.55; }}}}
    header, main {{{{ width: min(1040px, calc(100% - 32px)); margin: 0 auto; }}}}
    header {{{{ display: flex; justify-content: space-between; gap: 18px; padding: 18px 0; border-bottom: 1px solid var(--cpj-border); }}}}
    nav {{{{ display: flex; flex-wrap: wrap; gap: 12px; }}}}
    a {{{{ color: var(--cpj-primary); font-weight: 700; }}}}
    main {{{{ padding: 44px 0 80px; }}}}
    article, form, .cpj-panel {{{{ background: var(--cpj-surface); border: 1px solid var(--cpj-border); border-radius: 8px; padding: 22px; box-shadow: 0 18px 48px rgba(24, 33, 47, 0.10); margin-bottom: 16px; }}}}
    h1 {{{{ font-size: clamp(2rem, 6vw, 4rem); line-height: 1.02; margin-top: 0; letter-spacing: 0; }}}}
    input, textarea, select {{{{ display: block; width: 100%; margin: 6px 0 14px; padding: 11px 12px; border: 1px solid var(--cpj-border); border-radius: 8px; font: inherit; }}}}
    textarea {{{{ min-height: 160px; }}}}
    button {{{{ min-height: 42px; padding: 0 16px; border: 0; border-radius: 8px; background: var(--cpj-primary); color: white; font-weight: 800; cursor: pointer; }}}}
    .meta {{{{ color: var(--cpj-muted); }}}}
  </style>
</head>
<body>
  <header>
    <strong>{{site}}</strong>
    <nav><a href="/">Home</a><a href="{{blog_path}}">Posts</a><a href="{{admin_path}}">Admin</a><a href="/api/posts">API</a></nav>
  </header>
  <main>{{body}}</main>
</body>
</html>"""


def cms_post_card(post):
    slug = escape(str(post.get("slug", "")))
    title = escape(str(post.get("title", "Untitled")))
    body = escape(str(post.get("body", "")))
    created = escape(str(post.get("created_at", "")))
    blog_path = str(CMS_CONFIG.get("blog_path", "/blog")).rstrip("/")
    return f"""<article>
  <p class="meta">{{created}}</p>
  <h2><a href="{{blog_path}}/{{slug}}">{{title}}</a></h2>
  <p>{{body[:240]}}</p>
</article>"""


def cms_find_post(slug):
    for post in cms_load().get("posts", []):
        if str(post.get("slug")) == slug:
            return post
    return None


def cms_posts_page():
    posts = [post for post in cms_load().get("posts", []) if post.get("status", "published") == "published"]
    posts = sorted(posts, key=lambda item: item.get("created_at", ""), reverse=True)
    content = "<h1>Posts</h1>" + ("".join(cms_post_card(post) for post in posts) if posts else '<p class="meta">No posts yet.</p>')
    return cms_layout("Posts", content)


def cms_single_page(slug):
    post = cms_find_post(slug)
    if not post:
        return cms_layout("Not found", '<div class="cpj-panel"><h1>Post not found</h1></div>')
    title = escape(str(post.get("title", "Untitled")))
    body = escape(str(post.get("body", ""))).replace("\\n", "<br>")
    meta = escape(str(post.get("created_at", "")))
    return cms_layout(title, f'<article><p class="meta">{{meta}}</p><h1>{{title}}</h1><p>{{body}}</p></article>')


def cms_admin_page(message=""):
    notice = f'<p class="meta">{{escape(message)}}</p>' if message else ""
    admin_path = str(CMS_CONFIG.get("admin_path", "/admin")).rstrip("/")
    return cms_layout(
        "Admin",
        f"""<h1>CPJPress Admin</h1>
{{notice}}
<form method="post" action="{{admin_path}}/post">
  <label>Title<input name="title" required></label>
  <label>Slug<input name="slug"></label>
  <label>Author<input name="author" value="CPJ"></label>
  <label>Status<select name="status"><option value="published">published</option><option value="draft">draft</option></select></label>
  <label>Body<textarea name="body" required></textarea></label>
  <button type="submit">Publish</button>
</form>""",
    )


def cms_handle_get(path, query):
    if not CMS_CONFIG:
        return None
    admin_path = str(CMS_CONFIG.get("admin_path", "/admin")).rstrip("/")
    blog_path = str(CMS_CONFIG.get("blog_path", "/blog")).rstrip("/")
    if path == "/api/posts":
        return 200, "application/json; charset=utf-8", json.dumps(cms_load().get("posts", []), indent=2)
    if path.startswith("/api/posts/"):
        post = cms_find_post(path.rsplit("/", 1)[-1])
        return 200, "application/json; charset=utf-8", json.dumps(post or {{"error": "not_found"}}, indent=2)
    if path == admin_path:
        return 200, "text/html; charset=utf-8", cms_admin_page()
    if path == blog_path or path == blog_path + "/":
        return 200, "text/html; charset=utf-8", cms_posts_page()
    if path.startswith(blog_path + "/"):
        return 200, "text/html; charset=utf-8", cms_single_page(path[len(blog_path) + 1:])
    return None


def cms_handle_post(path, data):
    if not CMS_CONFIG:
        return None
    admin_path = str(CMS_CONFIG.get("admin_path", "/admin")).rstrip("/")
    if path not in {{admin_path + "/post", "/api/posts"}}:
        return None
    store = cms_load()
    title = str(data.get("title", "Untitled")).strip() or "Untitled"
    slug = cms_slug(data.get("slug") or title)
    post = {{
        "slug": slug,
        "title": title,
        "body": str(data.get("body", "")),
        "type": "post",
        "status": str(data.get("status", "published")),
        "author": str(data.get("author", "CPJ")),
        "created_at": datetime.now(timezone.utc).isoformat(),
    }}
    posts = [item for item in store.get("posts", []) if item.get("slug") != slug]
    posts.append(post)
    store["posts"] = posts
    cms_save(store)
    if path == "/api/posts":
        return 201, "application/json; charset=utf-8", json.dumps(post, indent=2)
    return 200, "text/html; charset=utf-8", cms_admin_page(f"Published {{title}}")


def sql_type(field_type):
    lowered = str(field_type).lower()
    if lowered in {{"int", "integer", "bool", "boolean"}}:
        return "INTEGER"
    if lowered in {{"float", "double", "decimal", "number", "real"}}:
        return "REAL"
    if lowered in {{"bytes", "blob", "binary", "file"}}:
        return "BLOB"
    return "TEXT"


def safe_identifier(value):
    name = str(value)
    if not re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", name):
        raise ValueError(f"Unsafe SQL identifier: {{name}}")
    return name


def existing_columns(db, table):
    table = safe_identifier(table)
    return {{row[1] for row in db.execute(f"PRAGMA table_info({{table}})").fetchall()}}


def apply_migrations(db):
    if not MIGRATIONS:
        return
    db.execute("CREATE TABLE IF NOT EXISTS cpj_migrations (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL)")
    applied = {{row[0] for row in db.execute("SELECT name FROM cpj_migrations").fetchall()}}
    for migration in MIGRATIONS:
        name = str(migration.get("name", "migration"))
        store = safe_identifier(migration.get("store", name))
        if name in applied:
            continue
        current_columns = existing_columns(db, store)
        for field in migration.get("add_fields", []):
            field_name = safe_identifier(field.get("name"))
            if field_name in current_columns:
                continue
            required = " NOT NULL DEFAULT ''" if field.get("required") else ""
            db.execute(f"ALTER TABLE {{store}} ADD COLUMN {{field_name}} {{sql_type(field.get('type', 'text'))}}{{required}}")
            current_columns.add(field_name)
        for index in migration.get("indexes", []):
            field_name = safe_identifier(index.get("field"))
            unique = "UNIQUE " if index.get("unique") else ""
            index_name = safe_identifier(f"idx_{{store}}_{{field_name}}")
            db.execute(f"CREATE {{unique}}INDEX IF NOT EXISTS {{index_name}} ON {{store}} ({{field_name}})")
        db.execute("INSERT OR REPLACE INTO cpj_migrations (name, applied_at) VALUES (?, ?)", [name, datetime.now(timezone.utc).isoformat()])


def resolve_services():
    resolved = {{}}
    for name, service in SERVICES.items():
        values = dict(service.get("values", {{}}))
        for key, env_spec in service.get("env", {{}}).items():
            env_name = str(env_spec.get("name", ""))
            values[key] = os.environ.get(env_name, env_spec.get("default", ""))
        resolved[name] = values
    return resolved


def init_stores():
    if not STORES and not MIGRATIONS:
        return
    db = sqlite3.connect(STORE_DB)
    try:
        for name, store in STORES.items():
            table_name = safe_identifier(name)
            fields = store.get("fields", [])
            columns = ["id INTEGER PRIMARY KEY AUTOINCREMENT", "created_at TEXT NOT NULL"]
            for field in fields:
                field_name = safe_identifier(field["name"])
                required = " NOT NULL" if field.get("required") else ""
                columns.append(f"{{field_name}} {{sql_type(field.get('type', 'text'))}}{{required}}")
            db.execute(f"CREATE TABLE IF NOT EXISTS {{table_name}} ({{', '.join(columns)}})")
        apply_migrations(db)
        for name, store in STORES.items():
            table_name = safe_identifier(name)
            count = db.execute(f"SELECT COUNT(*) FROM {{table_name}}").fetchone()[0]
            if count == 0:
                for row in store.get("seed", []):
                    store_create(name, row, db=db)
        db.commit()
    finally:
        db.close()


def store_create(name, data, db=None):
    close = db is None
    db = db or sqlite3.connect(STORE_DB)
    try:
        store = STORES[name]
        table_name = safe_identifier(name)
        fields = [safe_identifier(field["name"]) for field in store.get("fields", [])]
        row = {{"created_at": datetime.now(timezone.utc).isoformat()}}
        for field in fields:
            row[field] = data.get(field, "")
        columns = list(row.keys())
        placeholders = ", ".join("?" for _ in columns)
        db.execute(
            f"INSERT INTO {{table_name}} ({{', '.join(columns)}}) VALUES ({{placeholders}})",
            [row[column] for column in columns],
        )
        row["id"] = db.execute("SELECT last_insert_rowid()").fetchone()[0]
        if close:
            db.commit()
        return row
    finally:
        if close:
            db.close()


def store_rows(name):
    db = sqlite3.connect(STORE_DB)
    db.row_factory = sqlite3.Row
    try:
        table_name = safe_identifier(name)
        rows = db.execute(f"SELECT * FROM {{table_name}} ORDER BY id DESC").fetchall()
        return [dict(row) for row in rows]
    finally:
        db.close()


def store_update(name, row_id, data):
    db = sqlite3.connect(STORE_DB)
    db.row_factory = sqlite3.Row
    try:
        table_name = safe_identifier(name)
        fields = [safe_identifier(field["name"]) for field in STORES[name].get("fields", []) if field["name"] in data]
        if fields:
            assignments = ", ".join(f"{{field}} = ?" for field in fields)
            db.execute(f"UPDATE {{table_name}} SET {{assignments}} WHERE id = ?", [data[field] for field in fields] + [row_id])
            db.commit()
        row = db.execute(f"SELECT * FROM {{table_name}} WHERE id = ?", [row_id]).fetchone()
        return dict(row) if row else None
    finally:
        db.close()


def store_delete(name, row_id):
    db = sqlite3.connect(STORE_DB)
    try:
        table_name = safe_identifier(name)
        db.execute(f"DELETE FROM {{table_name}} WHERE id = ?", [row_id])
        db.commit()
    finally:
        db.close()
    return {{"deleted": True, "id": row_id}}


def handle_store(path, method, data=None):
    for name, store in STORES.items():
        base = str(store.get("path", f"/api/store/{{name}}")).rstrip("/")
        if path == base:
            if method == "GET":
                return 200, "application/json; charset=utf-8", json.dumps(store_rows(name), indent=2)
            if method == "POST":
                return 201, "application/json; charset=utf-8", json.dumps(store_create(name, data or {{}}), indent=2)
        if path.startswith(base + "/"):
            row_id = path.rsplit("/", 1)[-1]
            if method in {{"PUT", "PATCH"}}:
                row = store_update(name, row_id, data or {{}})
                return 200, "application/json; charset=utf-8", json.dumps(row or {{"error": "not_found"}}, indent=2)
            if method == "DELETE":
                return 200, "application/json; charset=utf-8", json.dumps(store_delete(name, row_id), indent=2)
    return None


def parse_multipart(content_type, body):
    boundary_marker = "boundary="
    if boundary_marker not in content_type:
        return {{"__invalid_multipart__": True}}
    boundary = content_type.split(boundary_marker, 1)[1].split(";", 1)[0].strip().strip('"').encode("utf-8")
    fields = {{}}
    files = []
    for part in body.split(b"--" + boundary):
        part = part.strip(b"\\r\\n")
        if not part or part == b"--" or b"\\r\\n\\r\\n" not in part:
            continue
        raw_headers, content = part.split(b"\\r\\n\\r\\n", 1)
        headers = raw_headers.decode("utf-8", "replace").split("\\r\\n")
        disposition = next((header for header in headers if header.lower().startswith("content-disposition:")), "")
        content_type_header = next((header for header in headers if header.lower().startswith("content-type:")), "")
        attrs = {{}}
        for chunk in disposition.split(";"):
            if "=" in chunk:
                key, value = chunk.strip().split("=", 1)
                attrs[key.lower()] = value.strip().strip('"')
        field_name = attrs.get("name", "")
        filename = attrs.get("filename")
        content = content.rstrip(b"\\r\\n")
        if filename:
            files.append(
                {{
                    "field": field_name,
                    "filename": filename,
                    "content_type": content_type_header.split(":", 1)[1].strip() if ":" in content_type_header else "application/octet-stream",
                    "content": content,
                    "size": len(content),
                }}
            )
        elif field_name:
            fields[field_name] = content.decode("utf-8", "replace")
    fields["__files__"] = files
    return fields


def safe_filename(filename):
    stem = re.sub(r"[^a-zA-Z0-9._-]+", "-", Path(filename).name).strip(".-") or "upload.bin"
    return f"{{uuid.uuid4().hex}}-{{stem}}"


def handle_upload(path, method, data):
    if method != "POST":
        return None
    for upload in UPLOADS:
        if path != str(upload.get("path")):
            continue
        files = data.get("__files__", [])
        saved = []
        target_dir = Path(str(upload.get("dir", "uploads")))
        target_dir.mkdir(parents=True, exist_ok=True)
        accepts = set(upload.get("accept", []))
        max_bytes = int(upload.get("max_bytes", 5 * 1024 * 1024))
        for item in files:
            if item["size"] > max_bytes:
                return 413, "application/json; charset=utf-8", json.dumps({{"error": "file_too_large", "filename": item["filename"]}}, indent=2)
            if accepts and item["content_type"] not in accepts:
                guessed = mimetypes.guess_type(item["filename"])[0]
                if guessed not in accepts:
                    return 415, "application/json; charset=utf-8", json.dumps({{"error": "unsupported_media_type", "filename": item["filename"]}}, indent=2)
            filename = safe_filename(item["filename"])
            destination = target_dir / filename
            destination.write_bytes(item["content"])
            saved.append(
                {{
                    "field": item["field"],
                    "filename": item["filename"],
                    "stored_as": str(destination).replace("\\\\", "/"),
                    "url": "/" + str(destination).replace("\\\\", "/"),
                    "content_type": item["content_type"],
                    "size": item["size"],
                }}
            )
        return 201, "application/json; charset=utf-8", json.dumps({{"files": saved, "fields": {{k: v for k, v in data.items() if k != "__files__"}}}}, indent=2)
    return None


def middleware_entries():
    named = {{item.get("name"): item for item in MIDDLEWARE}}
    entries = list(MIDDLEWARE)
    for pipeline in PIPELINES:
        for name in pipeline.get("uses", []):
            if name in named:
                entries.append(named[name])
        entries.append(pipeline)
    return entries


def middleware_headers():
    headers = {{}}
    for item in middleware_entries():
        headers.update(item.get("headers", {{}}))
        cors = item.get("cors")
        if cors:
            headers["Access-Control-Allow-Origin"] = cors
            headers["Access-Control-Allow-Methods"] = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
            headers["Access-Control-Allow-Headers"] = "Content-Type, Authorization, X-CPJ-Token"
        if item.get("request_id"):
            headers.setdefault("X-CPJ-Request-ID", uuid.uuid4().hex)
    return headers


def middleware_allows(handler, path):
    for item in middleware_entries():
        for rule in item.get("require_headers", []):
            rule_path = str(rule.get("path", "")).rstrip("/")
            if rule_path and not path.startswith(rule_path):
                continue
            header = str(rule.get("header", ""))
            expected = str(rule.get("value", ""))
            if header and handler.headers.get(header, "") != expected:
                handler._send_json(403, {{"error": "middleware_rejected", "pipeline": item.get("name"), "required_header": header}})
                return False
    return True


class CPJHandler(BaseHTTPRequestHandler):
    server_version = "CPJWeb/1.0"

    def _send(self, status, body, content_type):
        if isinstance(body, str):
            payload = body.encode("utf-8")
        else:
            payload = body
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(payload)))
        self.send_header("Cache-Control", "no-store")
        for name, value in middleware_headers().items():
            self.send_header(name, value)
        self.end_headers()
        self.wfile.write(payload)

    def _send_json(self, status, payload):
        self._send(status, json.dumps(payload, indent=2), "application/json; charset=utf-8")

    def _read_data(self):
        size = int(self.headers.get("Content-Length", "0") or 0)
        raw_bytes = self.rfile.read(size) if size else b""
        content_type = self.headers.get("Content-Type", "")
        if "multipart/form-data" in content_type:
            return parse_multipart(content_type, raw_bytes)
        raw = raw_bytes.decode("utf-8") if raw_bytes else ""
        if "application/json" in content_type and raw:
            try:
                payload = json.loads(raw)
            except json.JSONDecodeError:
                return {{"__invalid_json__": True}}
            return payload if isinstance(payload, dict) else {{"value": payload}}
        return {{key: values[-1] if values else "" for key, values in parse_qs(raw).items()}}

    def _guard_allows(self, path):
        for guard in GUARDS:
            guard_path = str(guard.get("path", "")).rstrip("/")
            if not guard_path or not path.startswith(guard_path):
                continue
            expected = str(guard.get("token", ""))
            provided = self.headers.get("X-CPJ-Token", "")
            auth = self.headers.get("Authorization", "")
            if auth.startswith("Bearer "):
                provided = auth.split(" ", 1)[1]
            if not expected or provided == expected:
                return True
            self._send_json(401, {{"error": "unauthorized", "path": path}})
            return False
        return True

    def _api_response(self, path, method, data=None):
        route = API_ROUTES.get(path)
        if not route:
            return False
        allowed = str(route.get("method", "GET")).upper()
        if allowed != method:
            self._send_json(405, {{"error": "method_not_allowed", "allowed": allowed, "method": method}})
            return True
        payload = dict(route.get("json", {{}}))
        inject = route.get("inject", [])
        if inject:
            resolved = resolve_services()
            payload["services"] = {{name: resolved.get(name, {{}}) for name in inject}}
        if data is not None:
            payload["request"] = data
        self._send_json(200, payload)
        return True

    def _handle_data_method(self, method):
        path = urlparse(self.path).path
        data = self._read_data()
        if data.get("__invalid_json__"):
            self._send_json(400, {{"error": "invalid_json"}})
            return
        if data.get("__invalid_multipart__"):
            self._send_json(400, {{"error": "invalid_multipart"}})
            return
        if not middleware_allows(self, path):
            return
        if not self._guard_allows(path):
            return
        upload_response = handle_upload(path, method, data)
        if upload_response:
            status, content_type, body = upload_response
            self._send(status, body, content_type)
            return
        store_response = handle_store(path, method, data)
        if store_response:
            status, content_type, body = store_response
            self._send(status, body, content_type)
            return
        if self._api_response(path, method, data):
            return
        cms_response = cms_handle_post(path, data)
        if cms_response:
            status, content_type, body = cms_response
            self._send(status, body, content_type)
            return
        self._send_json(200, {{"ok": True, "path": path, "method": method, "data": data}})

    def do_GET(self):
        parsed = urlparse(self.path)
        path = parsed.path
        if not middleware_allows(self, path):
            return
        if not self._guard_allows(path):
            return
        if path in ASSETS:
            asset = ASSETS[path]
            self._send(200, asset["body"], asset["content_type"])
            return
        if path == "/__cpj/services":
            self._send_json(200, resolve_services())
            return
        if path == "/__cpj/plugins":
            self._send_json(200, MARKETPLACE)
            return
        store_response = handle_store(path, "GET")
        if store_response:
            status, content_type, body = store_response
            self._send(status, body, content_type)
            return
        if self._api_response(path, "GET"):
            return
        cms_response = cms_handle_get(path, parse_qs(parsed.query))
        if cms_response:
            status, content_type, body = cms_response
            self._send(status, body, content_type)
            return
        if path in ROUTES:
            self._send(200, ROUTES[path], "text/html; charset=utf-8")
            return
        self._send_json(404, {{"error": "not_found", "path": path}})

    def do_POST(self):
        self._handle_data_method("POST")

    def do_PUT(self):
        self._handle_data_method("PUT")

    def do_PATCH(self):
        self._handle_data_method("PATCH")

    def do_DELETE(self):
        self._handle_data_method("DELETE")

    def do_OPTIONS(self):
        self._send(204, "", "text/plain; charset=utf-8")

    def log_message(self, fmt, *args):
        print("CPJ", self.address_string(), "-", fmt % args)


def run(host={self.server_host!r}, port={self.server_port!r}):
    init_stores()
    server = ThreadingHTTPServer((host, int(port)), CPJHandler)
    print(f"CPJ web server running at http://{{host}}:{{port}}")
    server.serve_forever()


if __name__ == "__main__":
    run()
'''

    def openapi_spec(self) -> dict[str, object]:
        paths: dict[str, object] = {}
        for route in self.api_routes:
            path = str(route["path"])
            method = str(route.get("method", "GET")).lower()
            paths.setdefault(path, {})
            paths[path][method] = {
                "summary": f"CPJ generated API {path}",
                "responses": {
                    "200": {
                        "description": "CPJ JSON response",
                        "content": {
                            "application/json": {
                                "example": route.get("json", {}),
                            }
                        },
                    }
                },
            }
        if self.cms:
            paths.setdefault("/api/posts", {})
            paths["/api/posts"]["get"] = {
                "summary": "List CPJ CMS posts",
                "responses": {"200": {"description": "Post list"}},
            }
            paths["/api/posts"]["post"] = {
                "summary": "Create a CPJ CMS post",
                "responses": {"201": {"description": "Created post"}},
            }
            paths.setdefault("/api/posts/{slug}", {})
            paths["/api/posts/{slug}"]["get"] = {
                "summary": "Read a CPJ CMS post by slug",
                "parameters": [{"name": "slug", "in": "path", "required": True, "schema": {"type": "string"}}],
                "responses": {"200": {"description": "Post"}},
            }
            for path, summary, item_name in [
                ("/api/comments", "List or create CPJ CMS comments", "Comment"),
                ("/api/media", "List or create CPJ CMS media metadata", "Media item"),
                ("/api/plugins", "List CPJ CMS plugin metadata", "Plugin"),
            ]:
                paths.setdefault(path, {})
                paths[path]["get"] = {
                    "summary": summary,
                    "responses": {"200": {"description": f"{item_name} list"}},
                }
            paths["/api/comments"]["post"] = {
                "summary": "Create a CPJ CMS comment",
                "responses": {"201": {"description": "Created comment"}},
            }
            paths["/api/media"]["post"] = {
                "summary": "Create CPJ CMS media metadata",
                "responses": {"201": {"description": "Created media item"}},
            }
            paths.setdefault("/feed.xml", {})
            paths["/feed.xml"]["get"] = {
                "summary": "Read the CPJ CMS RSS feed",
                "responses": {"200": {"description": "RSS feed"}},
            }
            paths.setdefault("/sitemap.xml", {})
            paths["/sitemap.xml"]["get"] = {
                "summary": "Read the CPJ CMS sitemap",
                "responses": {"200": {"description": "XML sitemap"}},
            }
        for name, store in self.stores.items():
            base = str(store.get("path", f"/api/store/{name}"))
            paths.setdefault(base, {})
            paths[base]["get"] = {"summary": f"List {name} records", "responses": {"200": {"description": "Record list"}}}
            paths[base]["post"] = {"summary": f"Create {name} record", "responses": {"201": {"description": "Created record"}}}
            paths.setdefault(base + "/{id}", {})
            paths[base + "/{id}"]["patch"] = {"summary": f"Update {name} record", "responses": {"200": {"description": "Updated record"}}}
            paths[base + "/{id}"]["delete"] = {"summary": f"Delete {name} record", "responses": {"200": {"description": "Deleted record"}}}
        for upload in self.uploads:
            path = str(upload.get("path"))
            paths.setdefault(path, {})
            paths[path]["post"] = {"summary": f"Upload binary files for {upload.get('name')}", "responses": {"201": {"description": "Uploaded files"}}}
        if self.services:
            paths["/__cpj/services"] = {
                "get": {"summary": "Inspect resolved CPJ dependency-injection services", "responses": {"200": {"description": "Service registry"}}}
            }
        if self.marketplace.get("plugins"):
            paths["/__cpj/plugins"] = {
                "get": {"summary": "Inspect CPJ plugin marketplace metadata", "responses": {"200": {"description": "Plugin registry"}}}
            }

        return {
            "openapi": "3.1.0",
            "info": {"title": self.title, "version": "1.0.0"},
            "paths": paths,
        }

    def design_tokens(self) -> dict[str, object]:
        colors = {
            key.replace("_", "-"): {"value": value, "type": "color"}
            for key, value in self.theme.items()
            if key not in {"radius", "shadow"}
        }
        return {
            "name": self.title,
            "source": "CPJ",
            "tokens": {
                "color": colors,
                "radius": {"card": {"value": "8px", "type": "borderRadius"}},
                "shadow": {"elevated": {"value": "0 18px 48px rgba(24, 33, 47, 0.10)", "type": "boxShadow"}},
            },
            "components": sorted(self.components.keys()),
            "models": self.models,
            "cms": self.cms or {},
            "pwa": self.pwa or {},
            "stores": self.stores,
            "uploads": self.uploads,
            "migrations": self.migrations,
            "services": self.services,
            "pipelines": self.pipelines,
            "templates": sorted(self.templates.keys()),
            "bundle": self.bundle,
            "marketplace": self.marketplace,
        }

    def component_inventory(self) -> dict[str, object]:
        return {
            "title": self.title,
            "components": [
                {"name": name, "html": markup}
                for name, markup in sorted(self.components.items())
            ],
            "routes": [{"path": route["path"]} for route in self.routes],
            "apis": [{"path": route["path"], "method": route.get("method", "GET")} for route in self.api_routes],
            "cms": self.cms or {},
            "pwa": self.pwa or {},
            "stores": list(self.stores.values()),
            "uploads": self.uploads,
            "guards": self.guards,
            "middleware": self.middleware,
            "pipelines": self.pipelines,
            "services": list(self.services.values()),
            "migrations": self.migrations,
            "templates": sorted(self.templates.keys()),
            "bundle": self.bundle,
            "marketplace": self.marketplace,
        }

    def diagnostics(self) -> dict[str, object]:
        messages = list(self.diagnostics_messages)
        if not self.title or self.title == "CPJ Web App":
            messages.append({"level": "warning", "area": "seo", "message": "Set a specific page title."})
        if len(self.description.strip()) < 20:
            messages.append({"level": "warning", "area": "seo", "message": "Meta description is short or missing."})
        if self.seen_h1 == 0:
            messages.append({"level": "warning", "area": "accessibility", "message": "Page has no h1 heading."})
        if self.seen_h1 > 1:
            messages.append({"level": "info", "area": "accessibility", "message": "Page has multiple h1 headings; verify document outline."})
        for upload in self.uploads:
            if not upload.get("accept"):
                messages.append({"level": "info", "area": "security", "message": f"Upload {upload.get('name')} allows any content type."})
        guarded_paths = [guard.get("path") for guard in self.guards]
        for upload in self.uploads:
            if upload.get("path") not in guarded_paths:
                messages.append({"level": "warning", "area": "security", "message": f"Upload endpoint {upload.get('path')} is not guarded."})
        declared_services = set(self.services)
        injected_services = {name for route in self.api_routes for name in route.get("inject", [])}
        for name in sorted(injected_services - declared_services):
            messages.append({"level": "warning", "area": "dependency-injection", "message": f"API injects undefined service {name}."})
        if self.migrations and not self.stores:
            messages.append({"level": "warning", "area": "database", "message": "Migrations are declared without stores."})
        return {
            "title": self.title,
            "summary": {
                "errors": sum(1 for item in messages if item["level"] == "error"),
                "warnings": sum(1 for item in messages if item["level"] == "warning"),
                "info": sum(1 for item in messages if item["level"] == "info"),
            },
            "messages": messages,
        }

    def project_readme(self) -> str:
        return f"""# {self.title}

Generated by CPJ as a standalone web engineering project.

## Run

```bash
python server.py
```

Then open `http://{self.server_host}:{self.server_port}`.

## Files

- `index.html` - standalone browser UI
- `server.py` - dependency-free local web server with routes and APIs
- `openapi.json` - API contract
- `design.tokens.json` - Figma-style design token handoff
- `components.json` - component and route inventory
- `diagnostics.json` - accessibility, SEO, and security diagnostics
- `plugins.marketplace.json` - CPJ plugin marketplace metadata and hooks
{ "- `manifest.webmanifest` and `sw.js` - install/offline PWA artifacts" if self.pwa else "" }
{ "- `cpj_store.sqlite3` - SQLite store database created on first server run" if self.stores else "" }
{ f"- `{self.bundle.get('name', 'app')}.bundle.js` and declarations - CPJ browser bundle with TypeScript-facing types" if self.bundle else "" }
{ "- Runtime endpoints: `/__cpj/services` and `/__cpj/plugins`" if self.services or self.marketplace.get("plugins") else "" }
{ "- `cpjpress_runtime.py` - dependency-free CPJPress CMS runtime" if self.cms else "" }
{ "- CMS routes: `/blog`, `/admin`, `/login`, `/search`, `/api/posts`, `/api/comments`, `/api/media`, `/api/plugins`, `/feed.xml`, `/sitemap.xml`" if self.cms else "" }
{ "- Default seeded admin: `admin` / `admin` unless a `user` directive is provided" if self.cms else "" }
"""

    def _route_document(self, path: str, route_body: str) -> str:
        state_script = "\n".join(
            f"  CPJ.state[{key!r}] = {value!r};" for key, value in self.states.items()
        )
        pwa_head = self._pwa_head()
        head_hooks = self._plugin_hook("head")
        body_end_hooks = self._plugin_hook("body_end")
        return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
{pwa_head}
{head_hooks}
  <title>{self._text(self.title)} - {self._text(path)}</title>
  <style>
{self._css()}
  </style>
</head>
<body>
  <div class="cpj-app" data-cpj-app>
{self._nav()}
    <main class="cpj-main">
      <section class="cpj-section">
{self._indent(route_body, 8)}
      </section>
    </main>
  </div>
  <script>
{self._js(state_script)}
  </script>
{body_end_hooks}
</body>
</html>
"""

    def _form_attrs(self, form_id: str, tokens: list[str]) -> dict[str, str]:
        attrs = {
            "id": form_id,
            "class": "cpj-form",
            "data-cpj-form": form_id,
        }
        target = self._target_from_tokens(tokens)
        method = "post"
        lowered = [token.lower() for token in tokens]
        if "action" in lowered:
            index = lowered.index("action")
            if index + 1 < len(tokens):
                target = tokens[index + 1]
        if "method" in lowered:
            index = lowered.index("method")
            if index + 1 < len(tokens):
                method = tokens[index + 1].lower()
        elif target and len(tokens) >= 3 and tokens[-1].lower() in {"get", "post", "put", "patch", "delete"}:
            method = tokens[-1].lower()
        if "multipart" in lowered or "upload" in lowered:
            attrs["enctype"] = "multipart/form-data"
            attrs["data-cpj-encoding"] = "multipart"
        if target:
            attrs["action"] = target
            attrs["method"] = method
            attrs["data-cpj-endpoint"] = target
            attrs["data-cpj-method"] = method.upper()
        return attrs

    def _field(self, name: str, label: str, input_type: str, flags: list[str] | None = None) -> str:
        attrs = {"id": name, "name": name, "type": input_type}
        self._apply_field_flags(attrs, flags or [])
        return (
            f'<label class="cpj-field" for="{self._attr(name)}">'
            f"<span>{self._text(label)}</span>"
            f"<input{self._attrs(attrs)}>"
            "</label>"
        )

    def _apply_field_flags(self, attrs: dict[str, str], flags: list[str]) -> None:
        index = 0
        while index < len(flags):
            flag = flags[index].lower()
            if flag in {"required", "disabled", "readonly", "multiple", "checked"}:
                attrs[flag] = flag
            elif flag in {"accept", "placeholder", "value", "min", "max", "step", "pattern"} and index + 1 < len(flags):
                attrs[flag] = flags[index + 1]
                index += 1
            index += 1

    def _counter(self, name: str, label: str, initial: str) -> str:
        return (
            f'<div class="cpj-counter" data-cpj-counter="{self._attr(name)}" '
            f'data-initial="{self._attr(initial)}" aria-label="{self._attr(label)}">'
            '<button type="button" data-counter-action="dec">-</button>'
            '<strong data-cpj-counter-value></strong>'
            '<button type="button" data-counter-action="inc">+</button>'
            "</div>"
        )

    def _target_from_tokens(self, tokens: list[str]) -> str | None:
        if len(tokens) >= 2 and tokens[0] in {"->", "to"}:
            return tokens[1]
        if len(tokens) == 1 and tokens[0].startswith("#"):
            return tokens[0]
        return None

    def _template_from_tokens(self, tokens: list[str]) -> str | None:
        lowered = [token.lower() for token in tokens]
        if "extends" in lowered:
            index = lowered.index("extends")
            if index + 1 < len(tokens):
                return self._slug(tokens[index + 1])
        return None

    def _apply_template(self, template_name: str, content: str) -> str:
        template = self.templates.get(self._slug(template_name))
        if not template:
            self.diagnostics_messages.append(
                {
                    "level": "warning",
                    "area": "template",
                    "message": f"Template {template_name} was requested but not defined.",
                }
            )
            return content
        if "{{content}}" in template:
            return template.replace("{{content}}", content)
        return template + "\n" + content

    def _plugin_hook(self, hook_name: str) -> str:
        hooks = self.marketplace.get("hooks", {}) if self.marketplace else {}
        entries = hooks.get(self._slug(hook_name), []) if isinstance(hooks, dict) else []
        return "\n".join(str(entry.get("html", "")) for entry in entries if isinstance(entry, dict))

    def _require_header(self, tokens: list[str]) -> dict[str, object]:
        rule: dict[str, object] = {"header": tokens[0], "value": tokens[1], "path": ""}
        lowered = [token.lower() for token in tokens]
        if "path" in lowered:
            index = lowered.index("path")
            if index + 1 < len(tokens):
                rule["path"] = tokens[index + 1]
        return rule

    def _coerce_value(self, value: str) -> object:
        lowered = value.lower()
        if lowered == "true":
            return True
        if lowered == "false":
            return False
        if lowered in {"null", "none"}:
            return None
        try:
            if "." in value:
                return float(value)
            return int(value)
        except ValueError:
            return value

    def _split(self, line: str) -> list[str]:
        try:
            return shlex.split(line, comments=False, posix=True)
        except ValueError:
            return line.split()

    def _tag(self, tag: str, text: str, css: str | None = None, attrs: dict[str, str] | None = None) -> str:
        attrs = dict(attrs or {})
        if css:
            attrs["class"] = css
        return f"<{tag}{self._attrs(attrs)}>{self._text(text)}</{tag}>"

    def _link(self, label: str, href: str, css: str) -> str:
        return f'<a class="{css}" href="{self._attr(href)}">{self._text(label)}</a>'

    def _block(self, tag: str, parts: list[str], attrs: dict[str, str] | None = None) -> str:
        return self._wrap(tag, "\n".join(part for part in parts if part), attrs)

    def _wrap(self, tag: str, inner: str, attrs: dict[str, str] | None = None) -> str:
        return f"<{tag}{self._attrs(attrs or {})}>\n{self._indent(inner, 2)}\n</{tag}>"

    def _attrs(self, attrs: dict[str, str]) -> str:
        if not attrs:
            return ""
        return "".join(f' {key}="{self._attr(value)}"' for key, value in attrs.items())

    def _indent(self, text: str, spaces: int) -> str:
        prefix = " " * spaces
        return "\n".join(prefix + line if line else line for line in text.splitlines())

    def _slug(self, value: str) -> str:
        slug = re.sub(r"[^a-zA-Z0-9_-]+", "-", value.strip().lower()).strip("-")
        return slug or "cpj"

    def _text(self, value: object) -> str:
        return html.escape(str(value), quote=False)

    def _attr(self, value: object) -> str:
        return html.escape(str(value), quote=True)


def emit_file(input_path: str | Path, output_path: str | Path) -> Path:
    ast_root = parse_file(str(input_path))
    html_code = WebEmitter().emit(ast_root)
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(html_code, encoding="utf-8")
    return output


def emit_project(input_path: str | Path, project_dir: str | Path) -> Path:
    ast_root = parse_file(str(input_path))
    emitter = WebEmitter()
    html_code = emitter.emit(ast_root)

    output_dir = Path(project_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    files = {
        "index.html": html_code,
        "server.py": emitter.server_source(html_code),
        "openapi.json": json.dumps(emitter.openapi_spec(), indent=2),
        "design.tokens.json": json.dumps(emitter.design_tokens(), indent=2),
        "components.json": json.dumps(emitter.component_inventory(), indent=2),
        "diagnostics.json": json.dumps(emitter.diagnostics(), indent=2),
        "plugins.marketplace.json": json.dumps(emitter.marketplace, indent=2),
        "README.md": emitter.project_readme(),
    }
    if emitter.bundle:
        bundle_name = str(emitter.bundle.get("name", "app"))
        files[f"{bundle_name}.bundle.js"] = emitter.bundle_source()
        if emitter.bundle.get("types", True):
            files[f"{bundle_name}.d.ts"] = emitter.bundle_types()
        files["tsconfig.json"] = json.dumps(
            {
                "compilerOptions": {
                    "target": str(emitter.bundle.get("target", "es2022")).upper(),
                    "module": "ESNext",
                    "moduleResolution": "Bundler",
                    "strict": True,
                    "allowJs": True,
                    "checkJs": True,
                },
                "include": [f"{bundle_name}.bundle.js", f"{bundle_name}.d.ts"],
            },
            indent=2,
        )
    for path, asset in emitter.runtime_assets().items():
        files[path.lstrip("/")] = asset["body"]
    if emitter.cms:
        files["cpjpress_runtime.py"] = (
            Path(__file__).with_name("cpjpress_runtime.py").read_text(encoding="utf-8")
        )
        files[str(emitter.cms.get("storage", "cpjpress_content.json"))] = json.dumps(
            emitter._cms_seed_store(),
            indent=2,
        )

    for name, contents in files.items():
        (output_dir / name).write_text(contents, encoding="utf-8")

    return output_dir


def main() -> None:
    parser = argparse.ArgumentParser(description="CPJ -> standalone HTML emitter")
    parser.add_argument("input", help="Input .cpj file")
    parser.add_argument("-o", "--output", required=True, help="Output .html file")
    parser.add_argument("--project-dir", help="Emit a full standalone web project to this directory")
    args = parser.parse_args()

    try:
        output = emit_file(args.input, args.output)
        if args.project_dir:
            project_dir = emit_project(args.input, args.project_dir)
    except Exception as exc:
        print(f"[WebEmitter] Error: {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"[WebEmitter] HTML emitted to {output}")
    if args.project_dir:
        print(f"[WebEmitter] Web project emitted to {project_dir}")


if __name__ == "__main__":
    main()
