#!/usr/bin/env python3
"""
CPJ Enhanced Emitter - Complete Standalone Language Code Generation

This emitter generates executable Python code from the complete CPJ AST,
supporting ALL features needed for a perfect standalone language:

- Exception handling (try/catch/finally)
- Dictionaries and all data structures
- String methods
- File I/O
- Import/module system
- Lambda functions
- Comprehensions
- All operators
- Async/await
- Pattern matching
- Context managers
- And more...
"""

import sys
from typing import List, Optional, Any
from io import StringIO


class EnhancedEmitter:
    """
    Enhanced code emitter that generates complete Python code from CPJ AST.
    Supports all features for standalone language operation.
    """

    def __init__(self):
        self.output = StringIO()
        self.indent_level = 0
        self.indent_str = "    "
        self.stdlib_imports = set()

    def emit(self, node, indent: int = 0) -> str:
        """Main emit function - dispatches to specific emitters"""
        self.indent_level = indent

        method_name = f'emit_{node.__class__.__name__}'
        if hasattr(self, method_name):
            return getattr(self, method_name)(node)
        else:
            return f"# Unknown node: {node.__class__.__name__}"

    def write(self, text: str):
        """Write text at current indentation"""
        self.output.write(self.indent_str * self.indent_level + text)

    def writeln(self, text: str = ""):
        """Write line at current indentation"""
        if text:
            self.write(text + "\n")
        else:
            self.output.write("\n")

    def get_code(self) -> str:
        """Get generated code"""
        return self.output.getvalue()

    # ========================================================================
    # Module and Import Emission
    # ========================================================================

    def emit_Module(self, node) -> str:
        """Emit complete module"""
        self.output = StringIO()

        # Emit header
        self.writeln("#!/usr/bin/env python3")
        self.writeln('"""')
        self.writeln("Generated by CPJ Enhanced Compiler")
        self.writeln("Complete standalone language support")
        self.writeln('"""')
        self.writeln()

        # Always import CPJ stdlib
        self.writeln("# CPJ Standard Library imports")
        self.writeln("import sys")
        self.writeln("import os")
        self.writeln("sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))")
        self.writeln("from stdlib.cpj_stdlib import *")
        self.writeln()

        # Emit user imports
        if node.imports:
            self.writeln("# User imports")
            for imp in node.imports:
                self.writeln(self.emit(imp))
            self.writeln()

        # Emit all items
        for item in node.items:
            code = self.emit(item)
            self.writeln(code)
            self.writeln()

        # Emit main execution
        self.writeln("# Main execution")
        self.writeln("if __name__ == '__main__':")
        self.indent_level += 1
        self.writeln("# Check for main() function")
        self.writeln("if 'main' in dir():")
        self.indent_level += 1
        self.writeln("main()")
        self.indent_level -= 2

        return self.get_code()

    def emit_ImportStmt(self, node) -> str:
        """Emit import statement"""
        if node.items:
            # from module import item1, item2
            items = ", ".join(node.items)
            return f"from {node.module} import {items}"
        elif node.alias:
            # import module as alias
            return f"import {node.module} as {node.alias}"
        else:
            # import module
            return f"import {node.module}"

    # ========================================================================
    # Class and Function Emission
    # ========================================================================

    def emit_ClassDef(self, node) -> str:
        """Emit class definition"""
        lines = []

        # Decorators
        for decorator in node.decorators:
            lines.append(f"@{self.emit_expr(decorator)}")

        # Class signature
        sig = f"class {node.name}"

        # Generics (as comment for now)
        if node.generics:
            sig += f"  # Generic[{', '.join(node.generics)}]"

        # Base classes
        if node.bases:
            sig += f"({', '.join(node.bases)})"

        sig += ":"
        lines.append(sig)

        # Docstring
        if node.docstring:
            lines.append(f'    """{node.docstring}"""')

        # Body
        if node.body:
            self.indent_level += 1
            for stmt in node.body:
                stmt_code = self.emit(stmt)
                for line in stmt_code.split('\n'):
                    if line.strip():
                        lines.append(self.indent_str + line)
            self.indent_level -= 1
        else:
            lines.append("    pass")

        return "\n".join(lines)

    def emit_FuncDef(self, node) -> str:
        """Emit function definition"""
        lines = []

        # Decorators
        for decorator in node.decorators:
            lines.append(f"@{self.emit_expr(decorator)}")

        # Function signature
        sig = ""
        if node.is_async:
            sig += "async "
        sig += f"def {node.name}("

        # Parameters
        param_strs = []
        for param in node.params:
            param_str = param.name

            if param.is_vararg:
                param_str = "*" + param_str
            elif param.is_kwarg:
                param_str = "**" + param_str

            if param.type_hint and not (param.is_vararg or param.is_kwarg):
                param_str += f": {param.type_hint}"

            if param.default:
                param_str += f"={self.emit_expr(param.default)}"

            param_strs.append(param_str)

        sig += ", ".join(param_strs)
        sig += ")"

        # Return type
        if node.return_type:
            sig += f" -> {node.return_type}"

        sig += ":"
        lines.append(sig)

        # Docstring
        if node.docstring:
            lines.append(f'    """{node.docstring}"""')

        # Body
        if node.body:
            self.indent_level += 1
            for stmt in node.body:
                stmt_code = self.emit(stmt)
                for line in stmt_code.split('\n'):
                    if line.strip():
                        lines.append(self.indent_str + line)
            self.indent_level -= 1
        else:
            lines.append("    pass")

        return "\n".join(lines)

    # ========================================================================
    # Control Flow Emission
    # ========================================================================

    def emit_If(self, node) -> str:
        """Emit if statement"""
        lines = []

        # If clause
        test = self.emit_expr(node.test)
        lines.append(f"if {test}:")

        # Body
        if node.body:
            self.indent_level += 1
            for stmt in node.body:
                stmt_code = self.emit(stmt)
                for line in stmt_code.split('\n'):
                    if line.strip():
                        lines.append(self.indent_str + line)
            self.indent_level -= 1
        else:
            lines.append(self.indent_str + "pass")

        # Else clause
        if node.orelse:
            lines.append("else:")
            self.indent_level += 1
            for stmt in node.orelse:
                stmt_code = self.emit(stmt)
                for line in stmt_code.split('\n'):
                    if line.strip():
                        lines.append(self.indent_str + line)
            self.indent_level -= 1

        return "\n".join(lines)

    def emit_While(self, node) -> str:
        """Emit while loop"""
        lines = []

        test = self.emit_expr(node.test)
        lines.append(f"while {test}:")

        # Body
        if node.body:
            self.indent_level += 1
            for stmt in node.body:
                stmt_code = self.emit(stmt)
                for line in stmt_code.split('\n'):
                    if line.strip():
                        lines.append(self.indent_str + line)
            self.indent_level -= 1
        else:
            lines.append(self.indent_str + "pass")

        # Else clause
        if node.orelse:
            lines.append("else:")
            self.indent_level += 1
            for stmt in node.orelse:
                stmt_code = self.emit(stmt)
                for line in stmt_code.split('\n'):
                    if line.strip():
                        lines.append(self.indent_str + line)
            self.indent_level -= 1

        return "\n".join(lines)

    def emit_For(self, node) -> str:
        """Emit for loop"""
        lines = []

        sig = ""
        if node.is_async:
            sig += "async "
        sig += f"for {node.target} in {self.emit_expr(node.iter_expr)}:"
        lines.append(sig)

        # Body
        if node.body:
            self.indent_level += 1
            for stmt in node.body:
                stmt_code = self.emit(stmt)
                for line in stmt_code.split('\n'):
                    if line.strip():
                        lines.append(self.indent_str + line)
            self.indent_level -= 1
        else:
            lines.append(self.indent_str + "pass")

        # Else clause
        if node.orelse:
            lines.append("else:")
            self.indent_level += 1
            for stmt in node.orelse:
                stmt_code = self.emit(stmt)
                for line in stmt_code.split('\n'):
                    if line.strip():
                        lines.append(self.indent_str + line)
            self.indent_level -= 1

        return "\n".join(lines)

    def emit_Match(self, node) -> str:
        """Emit match statement (Python 3.10+)"""
        lines = []

        expr = self.emit_expr(node.expr)
        lines.append(f"match {expr}:")

        # Cases
        self.indent_level += 1
        for case in node.cases:
            pattern = self.emit_expr(case.pattern)
            case_line = f"case {pattern}"

            if case.guard:
                case_line += f" if {self.emit_expr(case.guard)}"

            case_line += ":"
            lines.append(self.indent_str + case_line)

            # Case body
            if case.body:
                self.indent_level += 1
                for stmt in case.body:
                    stmt_code = self.emit(stmt)
                    for line in stmt_code.split('\n'):
                        if line.strip():
                            lines.append(self.indent_str + line)
                self.indent_level -= 1
            else:
                lines.append(self.indent_str * 2 + "pass")

        self.indent_level -= 1

        return "\n".join(lines)

    def emit_Break(self, node) -> str:
        """Emit break statement"""
        return "break"

    def emit_Continue(self, node) -> str:
        """Emit continue statement"""
        return "continue"

    def emit_Pass(self, node) -> str:
        """Emit pass statement"""
        return "pass"

    # ========================================================================
    # Exception Handling Emission
    # ========================================================================

    def emit_Try(self, node) -> str:
        """Emit try-except-else-finally"""
        lines = []

        # Try block
        lines.append("try:")
        if node.body:
            self.indent_level += 1
            for stmt in node.body:
                stmt_code = self.emit(stmt)
                for line in stmt_code.split('\n'):
                    if line.strip():
                        lines.append(self.indent_str + line)
            self.indent_level -= 1
        else:
            lines.append(self.indent_str + "pass")

        # Except handlers
        for handler in node.handlers:
            handler_line = "except"
            if handler.exc_type:
                handler_line += f" {handler.exc_type}"
                if handler.name:
                    handler_line += f" as {handler.name}"
            handler_line += ":"
            lines.append(handler_line)

            if handler.body:
                self.indent_level += 1
                for stmt in handler.body:
                    stmt_code = self.emit(stmt)
                    for line in stmt_code.split('\n'):
                        if line.strip():
                            lines.append(self.indent_str + line)
                self.indent_level -= 1
            else:
                lines.append(self.indent_str + "pass")

        # Else clause
        if node.orelse:
            lines.append("else:")
            self.indent_level += 1
            for stmt in node.orelse:
                stmt_code = self.emit(stmt)
                for line in stmt_code.split('\n'):
                    if line.strip():
                        lines.append(self.indent_str + line)
            self.indent_level -= 1

        # Finally clause
        if node.finalbody:
            lines.append("finally:")
            self.indent_level += 1
            for stmt in node.finalbody:
                stmt_code = self.emit(stmt)
                for line in stmt_code.split('\n'):
                    if line.strip():
                        lines.append(self.indent_str + line)
            self.indent_level -= 1

        return "\n".join(lines)

    def emit_Raise(self, node) -> str:
        """Emit raise statement"""
        if node.exc:
            result = f"raise {self.emit_expr(node.exc)}"
            if node.cause:
                result += f" from {self.emit_expr(node.cause)}"
            return result
        else:
            return "raise"

    def emit_Assert(self, node) -> str:
        """Emit assert statement"""
        result = f"assert {self.emit_expr(node.test)}"
        if node.msg:
            result += f", {self.emit_expr(node.msg)}"
        return result

    # ========================================================================
    # Context Manager Emission
    # ========================================================================

    def emit_With(self, node) -> str:
        """Emit with statement"""
        lines = []

        # With header
        sig = ""
        if node.is_async:
            sig += "async "
        sig += "with "

        item_strs = []
        for item in node.items:
            item_str = self.emit_expr(item.context_expr)
            if item.optional_vars:
                item_str += f" as {item.optional_vars}"
            item_strs.append(item_str)

        sig += ", ".join(item_strs)
        sig += ":"
        lines.append(sig)

        # Body
        if node.body:
            self.indent_level += 1
            for stmt in node.body:
                stmt_code = self.emit(stmt)
                for line in stmt_code.split('\n'):
                    if line.strip():
                        lines.append(self.indent_str + line)
            self.indent_level -= 1
        else:
            lines.append(self.indent_str + "pass")

        return "\n".join(lines)

    # ========================================================================
    # Assignment Emission
    # ========================================================================

    def emit_Assign(self, node) -> str:
        """Emit assignment"""
        targets = ", ".join(node.targets)
        value = self.emit_expr(node.value)

        if node.type_hint:
            return f"{targets}: {node.type_hint} = {value}"
        else:
            return f"{targets} = {value}"

    def emit_AugAssign(self, node) -> str:
        """Emit augmented assignment"""
        value = self.emit_expr(node.value)
        return f"{node.target} {node.op} {value}"

    def emit_AnnAssign(self, node) -> str:
        """Emit annotated assignment"""
        result = f"{node.target}: {node.annotation}"
        if node.value:
            result += f" = {self.emit_expr(node.value)}"
        return result

    def emit_Delete(self, node) -> str:
        """Emit delete statement"""
        targets = ", ".join(node.targets)
        return f"del {targets}"

    # ========================================================================
    # Function Flow Emission
    # ========================================================================

    def emit_Return(self, node) -> str:
        """Emit return statement"""
        if node.value:
            return f"return {self.emit_expr(node.value)}"
        else:
            return "return"

    def emit_Yield(self, node) -> str:
        """Emit yield statement"""
        if node.value:
            return f"yield {self.emit_expr(node.value)}"
        else:
            return "yield"

    def emit_YieldFrom(self, node) -> str:
        """Emit yield from statement"""
        return f"yield from {self.emit_expr(node.value)}"

    # ========================================================================
    # Statement Emission
    # ========================================================================

    def emit_ExprStmt(self, node) -> str:
        """Emit expression statement"""
        return self.emit_expr(node.expr)

    def emit_Print(self, node) -> str:
        """Emit print statement"""
        args = ", ".join(self.emit_expr(arg) for arg in node.args)
        return f"cpj_print({args})"

    def emit_GUIBlock(self, node) -> str:
        """Emit GUI block (use existing GUI emission)"""
        lines = []
        lines.append("# GUI Block")
        lines.append("# CPJ GUI generation would be invoked here")
        for line in node.body:
            lines.append(f"# {line}")
        return "\n".join(lines)

    # ========================================================================
    # Expression Emission
    # ========================================================================

    def emit_expr(self, node) -> str:
        """Emit expression"""
        if node is None:
            return "None"

        method_name = f'emit_expr_{node.__class__.__name__}'
        if hasattr(self, method_name):
            return getattr(self, method_name)(node)
        else:
            return f"<{node.__class__.__name__}>"

    def emit_expr_Num(self, node) -> str:
        """Emit number literal"""
        return str(node.value)

    def emit_expr_Str(self, node) -> str:
        """Emit string literal"""
        if node.is_fstring:
            return f'f"{node.value}"'
        else:
            return f'"{node.value}"'

    def emit_expr_Bool(self, node) -> str:
        """Emit boolean literal"""
        return "True" if node.value else "False"

    def emit_expr_NoneExpr(self, node) -> str:
        """Emit None"""
        return "None"

    def emit_expr_List(self, node) -> str:
        """Emit list literal"""
        elements = ", ".join(self.emit_expr(e) for e in node.elements)
        return f"[{elements}]"

    def emit_expr_Tuple(self, node) -> str:
        """Emit tuple literal"""
        elements = ", ".join(self.emit_expr(e) for e in node.elements)
        if len(node.elements) == 1:
            return f"({elements},)"
        return f"({elements})"

    def emit_expr_Set(self, node) -> str:
        """Emit set literal"""
        if not node.elements:
            return "set()"
        elements = ", ".join(self.emit_expr(e) for e in node.elements)
        return f"{{{elements}}}"

    def emit_expr_Dict(self, node) -> str:
        """Emit dictionary literal"""
        if not node.keys:
            return "{}"
        pairs = []
        for k, v in zip(node.keys, node.values):
            pairs.append(f"{self.emit_expr(k)}: {self.emit_expr(v)}")
        return "{" + ", ".join(pairs) + "}"

    def emit_expr_Var(self, node) -> str:
        """Emit variable reference"""
        return node.name

    def emit_expr_Attribute(self, node) -> str:
        """Emit attribute access"""
        value = self.emit_expr(node.value)
        return f"{value}.{node.attr}"

    def emit_expr_Subscript(self, node) -> str:
        """Emit subscript access"""
        value = self.emit_expr(node.value)
        index = self.emit_expr(node.index)
        return f"{value}[{index}]"

    def emit_expr_Slice(self, node) -> str:
        """Emit slice"""
        lower = self.emit_expr(node.lower) if node.lower else ""
        upper = self.emit_expr(node.upper) if node.upper else ""
        step = self.emit_expr(node.step) if node.step else ""

        if step:
            return f"{lower}:{upper}:{step}"
        else:
            return f"{lower}:{upper}"

    def emit_expr_BinOp(self, node) -> str:
        """Emit binary operation"""
        left = self.emit_expr(node.left)
        right = self.emit_expr(node.right)
        return f"({left} {node.op} {right})"

    def emit_expr_UnaryOp(self, node) -> str:
        """Emit unary operation"""
        operand = self.emit_expr(node.operand)
        return f"({node.op} {operand})"

    def emit_expr_Compare(self, node) -> str:
        """Emit comparison"""
        result = self.emit_expr(node.left)
        for op, comp in zip(node.ops, node.comparators):
            result += f" {op} {self.emit_expr(comp)}"
        return f"({result})"

    def emit_expr_BoolOp(self, node) -> str:
        """Emit boolean operation"""
        values = [self.emit_expr(v) for v in node.values]
        return f" {node.op} ".join(f"({v})" for v in values)

    def emit_expr_IfExpr(self, node) -> str:
        """Emit ternary operator"""
        body = self.emit_expr(node.body)
        test = self.emit_expr(node.test)
        orelse = self.emit_expr(node.orelse)
        return f"({body} if {test} else {orelse})"

    def emit_expr_NamedExpr(self, node) -> str:
        """Emit walrus operator"""
        value = self.emit_expr(node.value)
        return f"({node.target} := {value})"

    def emit_expr_Call(self, node) -> str:
        """Emit function call"""
        func = self.emit_expr(node.func)
        args = ", ".join(self.emit_expr(arg) for arg in node.args)

        if node.keywords:
            kwargs = ", ".join(
                f"{kw.arg}={self.emit_expr(kw.value)}"
                for kw in node.keywords
            )
            if args:
                args += ", " + kwargs
            else:
                args = kwargs

        return f"{func}({args})"

    def emit_expr_Lambda(self, node) -> str:
        """Emit lambda function"""
        params = ", ".join(p.name for p in node.params)
        body = self.emit_expr(node.body)
        return f"lambda {params}: {body}"

    def emit_expr_ListComp(self, node) -> str:
        """Emit list comprehension"""
        element = self.emit_expr(node.element)
        comp_parts = self.emit_comprehensions(node.generators)
        return f"[{element} {comp_parts}]"

    def emit_expr_SetComp(self, node) -> str:
        """Emit set comprehension"""
        element = self.emit_expr(node.element)
        comp_parts = self.emit_comprehensions(node.generators)
        return f"{{{element} {comp_parts}}}"

    def emit_expr_DictComp(self, node) -> str:
        """Emit dict comprehension"""
        key = self.emit_expr(node.key)
        value = self.emit_expr(node.value)
        comp_parts = self.emit_comprehensions(node.generators)
        return f"{{{key}: {value} {comp_parts}}}"

    def emit_expr_GeneratorExp(self, node) -> str:
        """Emit generator expression"""
        element = self.emit_expr(node.element)
        comp_parts = self.emit_comprehensions(node.generators)
        return f"({element} {comp_parts})"

    def emit_comprehensions(self, generators) -> str:
        """Emit comprehension clauses"""
        parts = []
        for gen in generators:
            part = f"for {gen.target} in {self.emit_expr(gen.iter)}"
            if gen.is_async:
                part = "async " + part
            for if_clause in gen.ifs:
                part += f" if {self.emit_expr(if_clause)}"
            parts.append(part)
        return " ".join(parts)

    def emit_expr_Await(self, node) -> str:
        """Emit await expression"""
        value = self.emit_expr(node.value)
        return f"await {value}"


# ============================================================================
# Main entry point
# ============================================================================

def emit_to_python(ast) -> str:
    """
    Main function to emit Python code from CPJ AST.
    Returns complete executable Python code.
    """
    emitter = EnhancedEmitter()
    return emitter.emit(ast)


if __name__ == '__main__':
    print("CPJ Enhanced Emitter v1.0")
    print("Complete standalone language code generation")
